### ISSUE TITLE
Add support for expression bodied members

### ISSUE THREAD

**Issue by Valdas3** [stryker-mutator/stryker-net#134] opened 2018-10-02 17:29 UTC
When testing I noticed that expression bodied members are skipped when looking for "mutatable" statements. So code like this
```c#
int Add(int x, int y)
{
    return x + y;
}
```
is successfully mutated to this
```c#
int Add(int x, int y)
{
    return x - y;
}
```
but code like this
```c#
int Add(int x, int y) => x + y;
```
is left unmutated.
I dug around a bit and it seems that this could be solved by checking if current node is ArrowExpressionClauseSyntax. 

If this looks like something you want to support when I could trying to make this work :)

**Comment by richardwerkman** [comment] 2018-10-02 18:52
Hi @Valdas3, at the moment LocalDeclarationStatements like yours are skipped on perpose because they break the program when mutated. 
This has to do with the way mutation are placed in the code.
``` csharp
int Add(int x, int y) => x + y;
```
Would look like this after mutations:
``` csharp
if(Environment.GetEnvironmentVariable("ActiveMutation") == "1") {
    int Add(int x, int y) => x - y;
} else {
    int Add(int x, int y) => x + y;
}
```

This affects the scope for the Add method. When it is called later on it will not compile.

To fix this the ArrowExpression should be mutated like this:
``` csharp
int Add(int x, int y) => Environment.GetEnvironmentVariable("ActiveMutation") == "1" ? x + y : x - y;
```

**Comment by richardwerkman** [comment] 2018-10-02 18:53
An issue for this already exists: #17

**Comment by Mobrockers** [comment] 2018-10-23 09:56
Close as duplicate of #17

**Closed by Mobrockers** 2018-10-23 09:56 UTC
Labels: duplicate
