### ISSUE TITLE
' System.FormatException: Input string was not in a correct format.'

### ISSUE THREAD

**Issue by DriezL** [stryker-mutator/stryker-net#1904] opened 2022-02-14 07:01 UTC
Created a simple classLibrary in VS2019 with an long add(int a, int b) function in it. Tested it with a simple unittest in a different project. This just to get to know Stryker. However, after running 1 minute, stryker crashes with this error: ' System.FormatException: Input string was not in a correct format.' I use dotnet-core 5.0. Update, created a dotnet-core 6.0 in VS2022 works just fine.

LOG:

   at Stryker.Core.TestRunners.VsTest.VsTestRunner.CantUseStrykerDataCollector()                                                                   in /_/src/Stryker.Core/Stryker.Core/TestRunners/VsTest/VsTestRunner.cs:line 77
   at Stryker.Core.TestRunners.VsTest.VsTestRunner.CaptureCoverage(IEnumerable`1                                                                   mutants) in /_/src/Stryker.Core/Stryker.Core/TestRunners/VsTest/VsTestRunner.cs                                                                  :line 288
   at Stryker.Core.TestRunners.VsTest.VsTestRunnerPool.CaptureCoverage(IEnumerab                                                                  le`1 mutants) in /_/src/Stryker.Core/Stryker.Core/TestRunners/VsTest/VsTestRunne                                                                  rPool.cs:line 85
   at Stryker.Core.CoverageAnalysis.CoverageAnalyser.DetermineTestCoverage() in                                                                   /_/src/Stryker.Core/Stryker.Core/CoverageAnalysis/CoverageAnalyser.cs:line 44
   at Stryker.Core.MutationTest.MutationTestProcess.GetCoverage() in /_/src/Stry                                                                  ker.Core/Stryker.Core/MutationTest/MutationTestProcess.cs:line 266
   at Stryker.Core.StrykerRunner.AnalyseCoverage(StrykerOptions options) in /_/s                                                                  rc/Stryker.Core/Stryker.Core/StrykerRunner.cs:line 147
   at Stryker.Core.StrykerRunner.RunMutationTest(IStrykerInputs inputs, ILoggerF                                                                  actory loggerFactory, IProjectOrchestrator projectOrchestrator) in /_/src/Stryke                                                                  r.Core/Stryker.Core/StrykerRunner.cs:line 64
   at Stryker.CLI.StrykerCli.RunStryker(IStrykerInputs inputs) in /_/src/Stryker                                                                  .CLI/Stryker.CLI/StrykerCLI.cs:line 90
   at Stryker.CLI.StrykerCli.<>c__DisplayClass9_0.<Run>b__0() in /_/src/Stryker.                                                                  CLI/Stryker.CLI/StrykerCLI.cs:line 65
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayCl                                                                  ass143_0.<OnExecute>b__0(CancellationToken _)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(S                                                                  tring[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String                                                                  [] args)
   at Stryker.CLI.StrykerCli.Run(String[] args) in /_/src/Stryker.CLI/Stryker.CL                                                                  I/StrykerCLI.cs:line 71
   at Stryker.CLI.Program.Main(String[] args) in /_/src/Stryker.CLI/Stryker.CLI/                                                                  Program.cs:line 15

**Desktop (please complete the following information):**
 - OS: Windows 10 v21H1
 - Type of project core
 - Framework Version: core 5.0
 - Stryker Version: 1.3.1.

**Comment by rouke-broersma** [comment] 2022-02-14 07:25
I'm missing the actual exception in your stacktrace. Could you add those lines.

**Comment by dupdob** [comment] 2022-02-14 08:38
it looks like Stryker.Net is failing to parse the framework version string. Could you provide us with the full exception report, or the log, or maybe the project itself, so we can reproduce it?

**Comment by DriezL** [comment] 2022-02-14 12:30
Alright, here's the complete solutio
[ClassLibrary1.zip](https://github.com/stryker-mutator/stryker-net/files/8060666/ClassLibrary1.zip)
n

**Comment by dupdob** [comment] 2022-02-14 22:19
Thanks. The problem comes from the framework version string in the project which is in a new format.
I opened a PR that supports this form of version string.

**Comment by rouke-broersma** [comment] 2022-02-18 10:17
Fixed by #1906

**Closed by rouke-broersma** 2022-02-18 10:17 UTC
Labels: 🐛 Bug
