### ISSUE TITLE
Crash during Test report generation

### ISSUE THREAD

**Issue by ZenwalkerD** [stryker-mutator/stryker-net#1928] opened 2022-02-23 07:03 UTC
**Describe the bug**
Launching dotnet stryker results in crash after completing analysis and during report generation on .net core 5 projects

**Logs**
Attached log file

**Expected behavior**
The stryker should output the report without crashing

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 Enterprise
 - Type of project .NET Core 5
 - Framework Version 5.0.405
 - Stryker Version 1.3.1

**Additional context**
[log-20220223.txt](https://github.com/stryker-mutator/stryker-net/files/8122426/log-20220223.txt)
[VsTest-log.txt](https://github.com/stryker-mutator/stryker-net/files/8122427/VsTest-log.txt)

 

> dotnet stryker --log-to-file
> 
>    _____ _              _               _   _ ______ _______  
>   / ____| |            | |             | \ | |  ____|__   __| 
>  | (___ | |_ _ __ _   _| | _____ _ __  |  \| | |__     | |    
>   \___ \| __| '__| | | | |/ / _ \ '__| | . ` |  __|    | |    
>   ____) | |_| |  | |_| |   <  __/ |    | |\  | |____   | |    
>  |_____/ \__|_|   \__, |_|\_\___|_| (_)|_| \_|______|  |_|    
>                    __/ |                                      
>                   |___/                                       
> 
> 
> Version: 1.3.1
> 
> [12:25:56 INF] Identifying project to mutate.
> \FunctionPoints.RetryManager.csproj will be mutated.
> [12:26:01 INF] Analysis complete.
> [12:26:01 INF] Building test project D:\Projects\Src\FunctionPointsManager\FunctionPointManagerBackend\FunctionPoints.RetryManager.Tests\FunctionPoints.RetryManager.Tests.csproj (1/1)
> [12:26:19 INF] Total number of tests found: 6.
> [12:26:19 INF] Initial testrun started.
> [12:26:22 INF] 47 mutants created
> [12:26:22 INF] Capture mutant coverage using 'CoverageBasedTest' mode.
> [12:26:23 INF] 1     mutants got status NoCoverage.   Reason: Mutant has no test coverage
> [12:26:23 INF] 46    mutants got status Ignored.      Reason: Removed by exclude from code coverage filter
> [12:26:23 INF] 47    total mutants are skipped for the above mentioned reasons
> [12:26:23 INF] 0     total mutants will be tested
> [12:26:23 WRN] It looks like all mutants with tests were ignored. Try a re-run with less ignoring!
> [12:26:24 INF] Time Elapsed 00:00:27.6926463
> Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
>    at Stryker.Core.Reporters.Progress.ProgressBar.Tick(String message) in /_/src/Stryker.Core/Stryker.Core/Reporters/Progress/ProgressBar.cs:line 31
>    at Stryker.Core.Reporters.Progress.ProgressBarReporter.ReportFinalState() in /_/src/Stryker.Core/Stryker.Core/Reporters/Progress/ProgressBarReporter.cs:line 68
>    at Stryker.Core.Reporters.Progress.ProgressReporter.OnAllMutantsTested(IReadOnlyProjectComponent reportComponent) in    at Stryker.Core.Reporters.BroadcastReporter.OnAllMutantsTested(IReadOnlyProjectComponent reportComponent) in /_/src/Stryker.Core/Stryker.Core/Reporters/BroadcastReporter.cs:line 63
>    at Stryker.Core.StrykerRunner.RunMutationTest(IStrykerInputs inputs, ILoggerFactory loggerFactory, IProjectOrchestrator projectOrchestrator) in /_/src/Stryker.Core/Stryker.Core/StrykerRunner.cs:line 97
>    at Stryker.CLI.StrykerCli.RunStryker(IStrykerInputs inputs) in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 90
>    at Stryker.CLI.StrykerCli.<>c__DisplayClass9_0.<Run>b__0() in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 65
>    at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass143_0.<OnExecute>b__0(CancellationToken _)
>    at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
>    at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
>    at Stryker.CLI.StrykerCli.Run(String[] args) in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 71
>    at Stryker.CLI.Program.Main(String[] args) in /_/src/Stryker.CLI/Stryker.CLI/Program.cs:line 15

**Comment by rouke-broersma** [comment] 2022-02-23 08:00
This is a duplicate of #1864 which has been fixed but has not been released yet.

The issue comes up because you have no mutants to test:

```
[12:26:22 INF] Capture mutant coverage using 'CoverageBasedTest' mode.
[12:26:23 INF] 1 mutants got status NoCoverage. Reason: Mutant has no test coverage
[12:26:23 INF] 46 mutants got status Ignored. Reason: Removed by exclude from code coverage filter
[12:26:23 INF] 47 total mutants are skipped for the above mentioned reasons
[12:26:23 INF] 0 total mutants will be tested
```

To workaround this bug until we have released the fix you can increase your test count so there are mutants to test (add test for mutant without coverage), remove exclude from code coverage attributes so less mutants go untested, or disable the progress bar reporter with `--reporter html`. See https://stryker-mutator.io/docs/stryker-net/configuration#reporter-string

**Closed by rouke-broersma** 2022-02-23 08:00 UTC
Labels: 🐛 Bug
