### ISSUE TITLE
DefineConstants are not parsed correctly

### ISSUE THREAD

**Issue by kish0** [stryker-mutator/stryker-net#1076] opened 2020-05-14 12:23 UTC
Stryker throws a compile error during the initial test run on vstest.
No special configurations, just specified the path for my *.csproj file on cmd. 
Attached the file with logs on the cmd during test run.
[StrykerLogs.txt](https://github.com/stryker-mutator/stryker/files/4628241/StrykerLogs.txt)
 
Please let me know if you need additional information.

**Comment by richardwerkman** [comment] 2020-05-14 19:39
Hi @kish0 thanks for submitting this issue. My first thought is that we read an empty value from your `DefineConstants` in your `.csproj` file. It could be possible it contains a value like: `TRACE;DEBUG;`. We split the value on `;` and that will leave 3 constants: `TRACE`, `DEBUG` and ``. The last one could cause the error.

It could be possible that dotnet build filters the empty values and we do not. If that is the case we should probably filter them as well. Could you verify that the `DefineConstants` is the problem?

**Comment by kish0** [comment] 2020-05-15 05:31
Hi @richardwerkman, as you suggested I removed DEBUG and TRACE constants from my project properties. But I still ended up with the same compile error. 

If it helps, I am including a part .csproj file of unit test


<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="..\..\Sources\packages\MSTest.TestAdapter.1.4.0\build\net45\MSTest.TestAdapter.props" Condition="Exists('..\..\Sources\packages\MSTest.TestAdapter.1.4.0\build\net45\MSTest.TestAdapter.props')" />
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <ProjectGuid>{C4D2A068-CAA4-483A-8810-2942B1D533F6}</ProjectGuid>
    <OutputType>Library</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>Philips.PMP.Test.Lan</RootNamespace>
    <AssemblyName>Philips.PMP.Test.Lan</AssemblyName>
    <TargetFrameworkVersion>v4.8</TargetFrameworkVersion>
    <FileAlignment>512</FileAlignment>
    <Deterministic>true</Deterministic>
    <NuGetPackageImportStamp>
    </NuGetPackageImportStamp>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>..\..\Product\</OutputPath>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <PlatformTarget>x64</PlatformTarget>
    <IsTestProject>True</IsTestProject>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>None</ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x64'">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>..\..\Product\</OutputPath>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <DebugType>full</DebugType>
    <PlatformTarget>x64</PlatformTarget>
    <LangVersion>latest</LangVersion>
    <ErrorReport>prompt</ErrorReport>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x64'">
    <OutputPath>bin\x64\Release\</OutputPath>
    <Optimize>true</Optimize>
    <DebugType>pdbonly</DebugType>
    <PlatformTarget>x64</PlatformTarget>
    <LangVersion>latest</LangVersion>
    <ErrorReport>prompt</ErrorReport>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="BouncyCastle.Crypto, Version=1.8.6.0, Culture=neutral, PublicKeyToken=0e99375e54769942, processorArchitecture=MSIL">
      <HintPath>..\..\Sources\packages\Portable.BouncyCastle.1.8.6\lib\net40\BouncyCastle.Crypto.dll</HintPath>
    </Reference>

**Comment by richardwerkman** [comment] 2020-05-15 07:01
Hi @kish0 I've succesfully reproduced the issue. It is caused by the `DefineConstants` property in your csproj. 

However it would be located in your project under test and not your test project. To be clear, this is what the cause looks like:

``` xml
    <DefineConstants>DEBUG;TRACE;</DefineConstants>
```
The last `;` causes an empty value when we parse the constants. The correct value looks like:

``` xml
    <DefineConstants>DEBUG;TRACE</DefineConstants>
```

You should be able to fix it by removing the last `;`. Meanwhile we should filter empty values in Stryker to make sure this error doesn't happen again. 🚀

**Comment by richardwerkman** [comment] 2020-05-15 07:14
This should be fixed in the next release, after the PR will be merged :)

**Comment by kish0** [comment] 2020-05-15 07:20
Thanks for the help @richardwerkman

**Closed** 2020-07-10 17:16 UTC
Labels: Area: Initial Build, bug
