### ISSUE TITLE
Stryker raises an InvalidOperationException during mutation phase

### ISSUE THREAD

**Issue by Alexael** [stryker-mutator/stryker-net#2836] opened 2024-01-23 11:03 UTC
First of all, thank you very much for one of the most awesome .NET tools around!
Unless I did something wrong and I'm the bug, I'll happily work on a PR myself as soon as I get some time.

**Describe the bug**
I have a property named "Order", member of record class "CreateOrderCommand".
Stryker 3.13.1 attempts to mutate the property name as if it were IEnumerable.Order()
When I rename the property to e.g. "OrderModel", the error does not occur.

**Logs**
[stryker.log](https://github.com/stryker-mutator/stryker-net/files/14022660/stryker.log)

**Expected behavior**
Stryker should not attempt to mutate a property name.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Type of project: .NET 6 class library
 - Framework Version: .NET 8.0.101
 - Stryker Version 3.13.1

**Comment by dupdob** [comment] 2024-01-23 14:02
Thanks for reporting this issue. 
The problem is not due to your property being named `Order`: it should be supported. This mutation would normally be reported as a compilation error.
What happens here is different: it triggers an internal error where Stryker fails to inject the mutation in the code. And this mutation ends up being tentatively injected in the next statement (hence the error)

It turns out I have a PR in draft that will probably fix this problem. It will try to reproduce this issue via an unit test to confirm I have a fix.

**Comment by dupdob** [comment] 2024-01-24 11:03
Analysis is over. It turns I have already pushed a fix for this and it will be part of the next release.
You can see issue #2825 for a workaround that will resolve the problem immediately.
(I close this issue as this problem is already tracked in 2825)

**Closed by dupdob** 2024-01-24 11:03 UTC
Labels: 🐛 Bug
