### ISSUE TITLE
Stryker should not mutate Excluded file

### ISSUE THREAD

**Issue by RinivR** [stryker-mutator/stryker-net#417] opened 2019-03-21 15:52 UTC
Hi,

It seems that the excluded file in `stryker-config.json` can be read by Stryker but somehow Stryker still try to mutate these excluded files. 
For example: 
When Stryker run: 

```
[16:17:13 INF] File \Example\Example.Agent.generated.cs will be excluded from mutation.
The error is shown:
[16:14:48 ERR] Unable to rollback mutation for node ReplyAction with error: The type or namespace name 'ReplyAction' could not be found (are you missing a using directive or an assembly reference?) (at Example\Example.Agent.generated.cs, line: 81, col: 111).
```

```json
{
    "stryker-config":
    {      
        "files-to-exclude": [
            "./Example/"
        ]
    }
}
```

**Comment by richardwerkman** [comment] 2019-03-21 20:47
Hi, thanks for letting us know!

My first thought is that the file should indeed not be mutated. You can see here: 
https://github.com/stryker-mutator/stryker-net/blob/8da93e52d13241afa013d2cb8a2d6b3220b2b34f/src/Stryker.Core/Stryker.Core/MutationTest/MutationTestProcess.cs#L70
That the mutating is enclosed by the check for excluded files. So I guess your file was somehow not excluded. I could check this in your debug output or you could check this yourself :)

**Comment by RinivR** [comment] 2019-03-26 09:23
Hi Richard,

I will send you the stryker-config.json file where the files which are excluded are mentioned.
When I run stryker i get the information log that the file is excluded from mutation, but then when stryker starts mutate then those files are tried to be mutated. 
I dont know why.
[10:08:13 INF] File C:\git\vec\MP\53-ISMATripleForms\Implementation\Vecozo.ISMATripleForms\04-Implementation\Agents\BSVerstrekking\BSVerstrekking.Agent.generated.cs will be excluded from mutation.

[10:09:50 ERR] Unable to rollback mutation for node "5.0.0.0" with error: Predefined type 'System.String' is not defined or imported (at C:\git\vec\MP\53-ISMATripleForms\Implementation\Vecozo.ISMATripleForms\04-Implementation\Agents\BSRelatie\BSRelatieV2_2.Agent.generated.cs, line: 53, col: 60).
[10:09:50 ERR] This should not happen, please report this as an issue on github with the previous error message.
[10:09:50 WRN] Safe Mode! Rolling back all mutations in method.

The stryker-config.json:
{
  "stryker-config": {
    "reporters": [
      "ConsoleProgressBar",
      "ConsoleReport"
    ],
    "log-level": "info",
    "timeout-ms": 10000,
    "log-file": true,
    "project-file": "04-Implementation.csproj",
    "max-concurrent-test-runners": 4,
    "threshold-high": 80,
    "threshold-low": 70,
    "threshold-break": 60,
    "files-to-exclude": [
      "C:\\git\\vec\\MP\\53-ISMATripleForms\\Implementation\\Vecozo.ISMATripleForms\\04-Implementation\\Agents\\BSRelatie\\BSRelatieV2_2.Agent.generated.cs",
      "C:\\git\\vec\\MP\\53-ISMATripleForms\\Implementation\\Vecozo.ISMATripleForms\\04-Implementation\\Agents"
    ]

  }
}

**Comment by richardwerkman** [comment] 2019-03-26 10:49
I see we have some more logging for excluded files. It looks like:
```
Excluded file C:\git\vec\MP\53-ISMATripleForms\Implementation\Vecozo.ISMATripleForms\04-Implementation\Agents\BSVerstrekking\BSVerstrekking.Agent.generated.cs, no mutants created
```

Do you see that in your output? If not it looks like the IsExcluded flag is somehow switched back after is has been set to true.

**Comment by richardwerkman** [comment] 2019-04-19 17:05
I have not been able to reproduce this issue yet. Closing this issue for now until a reproduction scenario is presented.

**Comment by aceldam** [comment] 2019-04-23 12:00
I experience the same issue. We have some script files (with cs extension) as embedded resources (for now), which I have listed in the exclude list. The output first indicates that they are ignored but they are still getting mutated, which fails.

**Comment by richardwerkman** [comment] 2019-04-23 12:36
@aceldam could you please provide a full logfile? You can create one by running:

```
dotnet stryker -f
```

I hope to see why your files are still being mutated in the logs.

**Comment by aceldam** [comment] 2019-04-23 13:17
You wan't Trace, Debug or Info?

**Comment by richardwerkman** [comment] 2019-04-23 14:00
File logging is trace logging by default ;) Setting the log level only affects console logging

**Comment by aceldam** [comment] 2019-04-23 18:04
[log-20190423.zip](https://github.com/stryker-mutator/stryker-net/files/3108952/log-20190423.zip)

**Comment by aceldam** [comment] 2019-04-23 18:05
Oh and btw I used a json config because I couldn't get the fte parameter to work

**Comment by aceldam** [comment] 2019-04-23 18:10
Got it working with command line args, but with same result

**Comment by richardwerkman** [comment] 2019-04-26 09:14
After inspecting your log file I would say the problem does not lie with file exclusion. It looks like we fail to compile your project with Roslyn. I see a lot of compile errors in your script files. 

The obvious thing is that Stryker should not try to compile your script files as they are not normal c# files. We scan your project for `*.cs` files however. That's why we include your scripting files.

I suggest you rename your scripting files to the `*.csx` extension. https://stackoverflow.com/questions/25405941/what-are-csx-c-sharp-files-for 
Stryker will then no longer pass the files to rolsyn and your project should run fine.

**Comment by aceldam** [comment] 2019-04-26 13:19
Good suggestion. Thanks

**Comment by richardwerkman** [comment] 2019-04-26 13:33
Closing this issue again, as there is still no problem with excluding files. 

@aceldam please let us know if you need more help using Stryker! 👍

**Closed by richardwerkman** 2019-04-26 13:33 UTC
Labels: To do, bug
