### ISSUE TITLE
Folders/Files outside of solution when looking for files to mutate

### ISSUE THREAD

**Issue by gregoks** [stryker-mutator/stryker-net#871] opened 2020-01-12 15:37 UTC
Hi guys,

When you are looking for files to mutate, you should take only folders and files which are part of the solution.
There are cases when there are folders/files that exist on the disk but are not part of the solution and you still try to mutate them and then the compilation fails.

The problem as I see it exists in the method ExtractProjectFolders in IputFileResolver class.

**Expected behavior**
Only take into account files and folders which are part of the solution.

**Desktop (please complete the following information):**
 - OS: Windows
 - Type of project: dot net core
 - Framework Version core 2,2
 - Stryker Version 0.15

**Comment by Mobrockers** [comment] 2020-01-15 06:29
This is something we want very much, but we don't know how to get the required information. Do you have any suggestion?

**Comment by gregoks** [comment] 2020-01-16 19:46
Hmmm..well perhaps if you have in one hand the project which you are testing then using reflection, you can take out all of the types that exist in the project.
Then when you are searching for the contents of the files that exist inside any project folder, you could check if the classes that exist inside those files, if they actually exist as a type of the tested project?

**Comment by dupdob** [comment] 2020-01-21 07:51
@Mobrockers : I have made an experiment using buildalizer results (SourceFiles) with perfect result on NFluent (which is made of shared projects, as you know).
Maybe Stryker could offer an option to switch between folders scan and project content?

**Comment by Mobrockers** [comment] 2020-01-21 08:14
I'm very interested in your result as I hadn't got that working yet so far!

**Comment by dupdob** [comment] 2020-01-21 09:11
humm. I need to try this again, then. My memory may be playing trick with me.

**Comment by Mobrockers** [comment] 2020-01-21 10:20
It could very well be that it works for your project since all this msbuild stuff is so highly context specific so I would love to know if/how you got it working

**Comment by dupdob** [comment] 2020-01-21 14:00
I am looking into it. Now I remember: when debugging, I can confirm BuildAlyzer seems to properly list my source files (count is consistent). I am working on writing the appropriate logic to use this data as a source to confirm it works properly.

**Comment by dupdob** [comment] 2020-01-21 21:50
I have implemented the logic;  I am testing it against NFluent.
If it works I propose to open an issue to describe the option between folder scan and buildalizer result.
(name suggestion for the option will be welcomed).

**Comment by dupdob** [comment] 2020-01-22 08:04
I am glad to report it worked as a charm. 
Incidentally, it also resulted in the first public report on the dashboard for NFluent. 
As discussed I will open an issue do discuss the feature.

**Comment by Mobrockers** [comment] 2020-01-27 17:13
When 0.16.0 is released could you please report if the new feature fixes this problem for you?

**Comment by gregoks** [comment] 2020-01-27 19:03
yeah sure! Thanks for the fix guys!

**Comment by Mobrockers** [comment] 2020-02-11 12:40
@gregoks 0.16.0 has  been released, could you please test if this correctly finds your files?

**Comment by gregoks** [comment] 2020-02-12 18:44
Thanks a lot guys! We will test it in our projects and let you know of any issues.

**Comment by richardwerkman** [comment] 2020-02-24 15:24
@gregoks have you been able to test? We would like to know if we can close this issue 🚀

**Comment by Mobrockers** [comment] 2020-03-09 13:41
@gregoks Have you been able to confirm the fix works for your project?

**Closed by Mobrockers** 2020-03-09 13:41 UTC
Labels: bug, fixed in master
