### ISSUE TITLE
stryker occasionally hangs silently

### ISSUE THREAD

**Issue by SaschaMaisel** [stryker-mutator/stryker-net#1317] opened 2020-11-12 09:40 UTC
**Describe the bug**
When executing Stryker on my .NET core solution, occasionally (I would say once out of 5 tries?) stryker simply hangs.

my run command:
dotnet stryker -p Contracts/Contracts.csproj -tp "['ContractsTest/ContractsTest.csproj']" -cp stryker-config.json 

my stryker-config.json:

{
  "stryker-config": {
    "test-runner": "vstest",
    "reporters": [
      "html",
      "cleartext"
    ],
    "log-level": "info",
    "timeout-ms": 10000,
    "coverage-analysis": "perTest",
    "threshold-high": 80,
    "threshold-low": 70,
    "threshold-break": 40,
    "mutate": [
      "!**/*Startup.cs",
      "!**/*Program.cs"
    ]
  }
}

**Logs**
 I can attach a bunch of additional config & log files. If you need anything extra just let me know!

[stdio.failing.log](https://github.com/stryker-mutator/stryker-net/files/5529553/stdio.failing.log)
[stdio.successful.log](https://github.com/stryker-mutator/stryker-net/files/5529554/stdio.successful.log)
[VsTest-log.txt](https://github.com/stryker-mutator/stryker-net/files/5529556/VsTest-log.txt)

**Expected behavior**
I want the result shown in "stdio.successful.log every time instead of breaking silently every few runs.

**Desktop (please complete the following information):**
 - inside a docker container running Debian 10 Buster
 - .NET Core 3.1
 - Stryker .NET 0.20.0

**Additional context**
I don't know if this is related to Issue #1136 or not. My problem is not deterministic, sometimes everything works fine. Also I am mutating all my projects seperately.

**Comment by fabianeichfeldt** [comment] 2020-11-23 08:49
Same problem here :-(

**Comment by Mobrockers** [comment] 2020-11-23 14:26
Hi @SaschaMaisel and @fabianeichfeldt 

We are aware of this problem, but we do not yet have a solution.

**Comment by fabianeichfeldt** [comment] 2020-11-26 13:46
Do you have clue where the problem comes from? May be I can rearrange the code to avoid the problem.
Or even better, strip my project down to a minimum to debug the problem?

**Comment by Mobrockers** [comment] 2020-11-26 18:19
The problem unfortunately seems to be internal to vstest.

**Comment by Mobrockers** [comment] 2021-03-22 13:21
Duplicate of #1136

**Closed by Mobrockers** 2021-03-22 13:21 UTC
Labels: bug
