### ISSUE TITLE
Stryker fails to mutate in version 0.21.1

### ISSUE THREAD

**Issue by laurenceSaes** [stryker-mutator/stryker-net#1426] opened 2021-02-22 08:06 UTC
**Describe the bug**
Stryker will fail to mutate after upgrading from version 0.19 to 0.21.1. The ExpressionBody of a sourceNode is null what will result in a null reference exception:

The exception:
![image](https://user-images.githubusercontent.com/518177/108678634-9f14a900-74eb-11eb-8f59-49c0657592d3.png)

The source code to mutate:

```
get
      {
        var useValue = SettingsModel[XServerSettingsModel.FeatureBatchSizeSettingName].Value as int? ?? XModule.DefaultFeatureBatchSize;
        return useValue > 0 ? useValue : XModule.DefaultFeatureBatchSize;
      }
```

**Logs**

The following error is printed into the log file: [ErrorLog.txt](https://github.com/stryker-mutator/stryker-net/files/6020356/ErrorLog.txt)

**Expected behavior**
I would expect that Stryker does not fail to mutate this line of code. When it does, I would expect that Stryker would continue executing and log after completion that a specific mutation could not be performed.

**Desktop (please complete the following information):**

 - OS: Windows 10
 - Type of project: framework
 - Framework Version: net4.8
 - Stryker Version: 0.21.1

**Comment by dupdob** [comment] 2021-02-22 15:21
Hi, thanks for your detailed report. 
I need your help. I tried to reproduce the issue with the bit of code you provided and it works as expected with the WIP version. I am confident no one has tried to fix it yet, so I suspect the crash may  be due to some other part of the code.
Can you provide the complete definition of the property?

**Comment by laurenceSaes** [comment] 2021-02-24 08:18
Hello,

This is the complete definition of the property:

```
    /// <summary>
    /// Gets the configured feature batch size.
    /// </summary>
    public int FeatureBatchSize
    {
      get
      {
        var useValue = SettingsModel[XServerSettingsModel.FeatureBatchSizeSettingName].Value as int? ?? XModule.DefaultFeatureBatchSize;
        return useValue > 0 ? useValue : XModule.DefaultFeatureBatchSize;
      }
    }
```

The mutation generation succeeds on the master branch, so it seems like that this issue is already resolved.

**Comment by dupdob** [comment] 2021-02-24 10:41
Thanks for reverting with the requested details. You are right, the issue is indeed resolved and will be part of the next release.
Your problem relates to issue #1386.
This crash happens because Stryker have 'left over' mutations to inject and it assumes the property accessor is in the arrow expression format ( ex `get => return 1;`), where as the actual accessor is in the classical body format (`get { return 1;}`).

Stryker can only have 'left over' mutations when mutating an expression, so this should not happen when mutation a body. But Stryker v0.21.1 had an issue where some 'left-over' mutations could spill to the next method/properties, so Stryker tried to inject them and assumed the accessor was in the expression arrow format, since it should not happen in body format.

It is likely you have an array initialiser just above this property, such as ` private string[] Values = {"1";"2";}; `, you may resolve your issue by moving this declaration at some other place (i.e. away for any properties accessor declaration).

**Closed** 2021-02-25 10:03 UTC
Labels: Area: Mutating, bug
