### ISSUE TITLE
Assembly title and other assembly info might already exist in project under test

### ISSUE THREAD

**Issue by Mobrockers** [stryker-mutator/stryker-net#826] opened 2019-11-28 18:57 UTC
**Describe the bug**
Currently we assume if a project is dotnet core that we need to add assembly version information like here:

https://github.com/stryker-mutator/stryker-net/blob/d53686c57b24076630c927d99d72f1e7c7f41e11/src/Stryker.Core/Stryker.Core/Compiling/CompilingProcess.cs#L55

I have found some cases where Assembly metadata exists even though the project is dotnet core. This results in duplicate metadata. We should delete all existing metadata if it exists to be sure.

**Comment by dupdob** [comment] 2019-11-29 07:59
Can you provide a sample projet ? As far as I know, assembly attributes are injected during build for NetCore and NetStandard. Is there an option to prevent this?

**Comment by Mobrockers** [comment] 2019-11-29 08:02
I was trying the AssemblyIdentityComparer on https://github.com/microsoft/VFSForGit because if any project was gonna run into issues it would be their funky one, and it crashed because AssemblyTitle was duplicate.

**Comment by Mobrockers** [comment] 2019-11-29 08:07
> Can you provide a sample projet ? As far as I know, assembly attributes are injected during build for NetCore and NetStandard. Is there an option to prevent this?

Yes, there are MSBuild properties to disable the auto-generation

**Comment by dupdob** [comment] 2019-11-29 09:19
Thanks.
I took a look at the project, and yep, this is funky 👍

**Comment by Itsey** [comment] 2020-05-01 20:14
Is it possible that this can cause builds to fail?  I have been trying stryker.net and now can not get my code to compile at all (due to duplicate attributes)  - I never had this issue now all of a sudden it is here and I noticed this bug and thought I would ask.  I have even uninstalled the tool and still continue to get compilation failures - and I cant see where they are coming from.   Obviously this could be a coincidence and nothing to do with stryker, but hopefully someone can point me at where to look.

**Comment by Mobrockers** [comment] 2020-05-01 22:35
Yes, duplicate assembly attributes result in a compile error. We would love to have a simple reproduction as it does not happen on most projects.

**Comment by Itsey** [comment] 2020-05-02 10:19
I have done more testing now, my code compiles fine on a second machine (where stryker has never been installed) but fails to compile on a machine where stryker was installed (and now removed) - I'll clone it into GH if you wish to try it yourself.  Any idea what might be left behind after a dotnet -g tool uninstall?

**Comment by Mobrockers** [comment] 2020-05-02 13:34
Are you saying your code fails to compile at all, even outside of stryker?

Rebuilding should remove any trace of the modifications we made to your project, so it seems unlikely that stryker would be the cause of compilation failures in visual studio/ dotnet build etc.

Have you tried doing a clean before building?

**Comment by Itsey** [comment] 2020-05-02 15:35
Hi, yes - its very confusing - its likely I have done something stupid but it appears that I can no longer compile that solution even after removing stryker. Yet the same solution compiles fine on other machines.  I have put the latest code in GH now so you could clone and run stryker yourself and see if it had any issues or if I'm just losing the plot.   Its a pretty tiny and simple solution.  https://github.com/Itsey/Plisky.Versioning.   I'm going to do more tests as well to try to get to the bottom of it.
I have tried cleaning / recloning / deleting the dir and cloning again - code compiles on laptop and build server, just not on main machine any more.

**Comment by Itsey** [comment] 2020-05-02 19:03
Hi - I have recreated the initial problem now on a clean machine so I'm pretty sure its something related to stryker.   Steps I took
Clone Repo (above)
change to the versioning folder
dotnet build pliskyversioning.sln
(Compiles cleanly)
dotnet test pliskyversioning.sln
(121 pass)
dotnet tool install g dotnet-stryker
(installs)
cd plisky.versioning.test
dotnet stryker --project-file=<path>\Plisky.Versioning.Csproj
(stryker runs, 41.11%)
cd..
dotnet build pliskyverisoning.sln
(now has 6 compiler errors)

hope that helps you recreate the issue.

**Comment by Itsey** [comment] 2020-05-02 21:26
Hi
I have got to the bottom 
of this now.  You can reproduce this using the repo above but its very specific to that repo.  That repo is a versioning tool  - the unit tests include updates to known file types to write in the attributes.  Without stryker running it cleans up after itself.

The actual problem is caused by two files .NETCoreApp,Version=v3.1.AssemblyAttributes.cs and .NETStandard,Version=v2.0.AssemblyAttributes in your %TEMP% folder.  This is why it persisted even after stryker was removed and the directory cleaned.  These two files had been updated with the attributes which caused duplicates with the ones in the project.

I believe what happens here is that the mutations stryker applies update the file paths (which are strings) that are being used to locate the files to write to.  Therefore the test updates an entirely different file to the one it is intending to - which then breaks all .net core builds on the machine.

I haven't been able to prove that yet but it seems quite plausible and would explain why those two files got updated - I guess this is a risk when running mutations against tests that use the filesystem.  No idea if this issue would affect anyone else but hopefully it helps if they see this comment.

**Comment by dupdob** [comment] 2020-05-03 20:41
Thanks for being very thorough in your testing and chasing this issue. Interestingly, the original issue was triggered by Stryker not being able to properly detect when assembly attributes were generated on the fly vs. being in some source files.

I guess we can close the issue then.

**Comment by Mobrockers** [comment] 2020-05-04 06:44
> I believe what happens here is that the mutations stryker applies update the file paths (which are strings) that are being used to locate the files to write to. Therefore the test updates an entirely different file to the one it is intending to - which then breaks all .net core builds on the machine.
> 
> **Update:** - Found the underlying issue in code.
> The code says if (match a file to be updated) { update file } the mutation says if (!match a file to be updated) { update file } therefore files that should not be updated in the temp directory get updated, causing the issue.
> 
> Exceedingly unlikely that this affects anyone else now I understand the root cause but definitely red flagged unintended side effects of mutated tests!

Ouch! Haha :) Glad you found the issue. You can add an exclusion for that part of the file, for the whole file or disable the string mutator to work around this problem.

You could also see if it's possible to simply mock away all your filesystem calls with https://github.com/System-IO-Abstractions/System.IO.Abstractions so that all changes happen in-memory.

**Comment by dupdob** [comment] 2020-11-04 09:58
I guess this issue should be closed now as I think PR #1028 addressed the initial issue, thanks to a redesign of the attribute generation logic (so it is aligned to Net behaviour)

**Closed** 2020-12-26 16:30 UTC
Labels: bug
