### ISSUE TITLE
TestCaseSource causes incorrectly surviving mutations

### ISSUE THREAD

**Issue by onorton** [stryker-mutator/stryker-net#1434] opened 2021-02-23 11:09 UTC
**Describe the bug**
Using TestCaseSourceAttribute in NUnit for tests cases causes mutants not to be correctly killed.

![image](https://user-images.githubusercontent.com/5832785/108833994-79f46900-75c5-11eb-9c44-83781b355ac8.png)
![image](https://user-images.githubusercontent.com/5832785/108834828-89c07d00-75c6-11eb-82b2-552fbf37dd47.png)

Minimal example attached (N.B. this applies to any mutant and not just strings)
[TestCaseSourceExample.zip](https://github.com/stryker-mutator/stryker-net/files/6028485/TestCaseSourceExample.zip)

**Logs**
[log-20210223.txt](https://github.com/stryker-mutator/stryker-net/files/6028467/log-20210223.txt)
[VsTest-log.txt](https://github.com/stryker-mutator/stryker-net/files/6028468/VsTest-log.txt)

**Expected behavior**
Expected the mutant to be killed as we have a test that checks that the `Name` property is equal to the expected value 

**Desktop (please complete the following information):**
 - OS:  Windows 10 and Ubuntu 20.04 Docker Container 
 - Type of project: core
 -  Framework Version: core 3.1
 - Stryker Version: beta 0.21.1

**Additional context**
We can work around this by writing explicit tests per test case but it is not ideal due to duplication and we have a lot of tests that use this method.

**Comment by dupdob** [comment] 2021-02-23 12:21
Thanks for you report and kudos for providing such specific reproduction conditions.
I will look into this, but I am not confident about finding a (satisfactory) fix. We have a similar issues with xUnit (see #843), which is linked to the VSTest xUnit runner implementation.
I will report findings when I have time to replicate

**Comment by dupdob** [comment] 2021-02-23 16:09
So, I did reproduce, and I think I understand where the issue lies. The problem is that the code runs as part of the `TestCaseSource` attribute is executed **outside** the test(s). Using your example, the constructor for `Container`, which contains the mutation (replacing "cat" by an empty string), is called **before** the actual test, so the end result is that mutation is never actually applied.
Here is a (grossly simplified) workflow of what happens during the test phase:
1. TestSession starts, there is **no active mutant**
1. VsTest prepares execution of `NameIsExpected`
1. loop
    1. VsTest invokes `ContainerThings` to retrieve the next parameter  ⇒ `new Container()` is invoked. Since there is no active mutant, the unmodified code is executed
    1. VsTest notifies Stryker that `NameIsExpected` is about to run
    2. Stryker marks Mutant 0 as active (replacing "cat" by "" in the constructor), **this happens too late**
    3. VsTest executes the test which is successful
    4. VsTest reports success to Stryker, which flags the Mutant 0 as survived
    5. Loop until there is no new value
 6. Test session ends

As you can see, there is (currently) no clear notifications that happens **before** `ContainerThings` is invoked, that is the main reason of your problem.
To work around that, you need to ensure that as little as possible production code is run inside the `TestCaseSource` method.
Here is a modified version of your example that works fine:
```csharp
using System;
using System.Collections.Generic;
using NUnit.Framework;

namespace MutatorLibrary.Tests
{
    public class ContainerTests
    {

        private static IEnumerable<Type> ContainerThings()
        {
            yield return typeof(Container);
        }

        [Test,
         TestCaseSource(nameof(ContainerThings))]
        public void NameIsExpected(Type type)
        {
           // invoke the constructor using reflection.
            var thing = type.GetConstructor(new Type[] { }).Invoke(null) as Container;
            Assert.AreEqual("cat", thing.Thing.Name, "Thing name");
        }
    }
}
```

I will add a new message to explain what can/could be done to improve/fix this

**Comment by dupdob** [comment] 2021-02-23 16:18
Here is a list of thing that we can try, as improvements:

Check if we can activate some notifications for this
---
This would probably lead to a proper fix, but past experience with xUnit proves it is a longshot

Detects when this happen
---
Then we can take further steps. Caveat, we may have false negative here: the mutation may be executed during the test, but it happens to late and has no impact on the test. In the previous example, this would happen if (for some reason) another `Container` object was created during the test (so the mutation is run), but since only the first (non mutated) instance is asserted, the test still succeeds

This can be done: I already tried it to help analyse strange issues, but when I realised the limitation above, I lost interest.
Nonetheless we could then:
1. warn the user
2. re run the mutant in a specific test sessions.

Activate the mutation earlier
---
For example, we could active the _next_ mutation as soon as the previous test is finished.
Caveat: it relies on the hypothesis we know/control the order in which tests are executed. This seems to be actually the case, but the VsTest documentation makes no provision for that, and the behaviour may change in future Net version (or older ones)

**Comment by dupdob** [comment] 2021-02-23 17:26
For illustration, I have a similar issue with [NCrunch](https://www.ncrunch.net/):
![image](https://user-images.githubusercontent.com/3131866/108882291-85b35000-7604-11eb-8d5f-fed67264668d.png)

white dots mark non covered lines (green mark successful test)

**Comment by onorton** [comment] 2021-02-24 10:24
Thanks for looking into this and explaining Stryker's workflow in this case. The reason I am looking into using TestCaseSource here is that Container will contain multiple Things. 

Found a better workaround than we had initially (using reflection to access the fields for the test data). We found that it had to be a `[SetUp]` rather than `[OneTimeSetUp]`. I'm guessing this is because Stryker does not reset the test context for each mutant.

```cs
using System.Collections.Generic;
using NUnit.Framework;

namespace MutatorLibrary.Tests
{
    public class ContainerTests
    {

        private Container _container;

        [SetUp]
        public void SetUp()
        {
            _container = new Container();
        }

        private static IEnumerable<string> ContainerThings()
        {
            yield return nameof(Container.Thing);
        }

        [Test,
         TestCaseSource(nameof(ContainerThings))]
        public void NameIsExpected(string fieldName)
        {
            var thing = GetThing(fieldName);
            Assert.AreEqual("cat", thing.Name, "Thing name");
        }

        private Thing GetThing(string fieldName)
        {
            return (Thing)_container.GetType().GetField(fieldName)?.GetValue(_container);
        }
    }
}
```

**Comment by dupdob** [comment] 2021-02-24 10:47
Thanks for the feedback. Indeed, Stryker has little control over the test execution workflow, we are limited by what we can do with VsTest.
I am looking into how to provide a better fix for this, but this would require significant design changes (assuming it can be done in the first place), so there are undergoing discussions about the best strategy for this; so not sure when it will be available (i.e. probably not in the next version).

**Closed** 2021-06-25 13:12 UTC
Labels: bug
