### ISSUE TITLE
"Not all code paths return a value"

### ISSUE THREAD

**Issue by petertiedemann** [stryker-mutator/stryker-net#935] opened 2020-02-10 10:03 UTC
**Describe the bug**
The CLI tool requested that i report this as a bug:

```
[10:50:30 WRN] Stryker.NET encountered an compile error in C:\git\core\src\Utils\Base\EnumerableComparer.cs (at 25:15) with message: 'EnumerableComparer<T>.Compare(IEnumerable<T>, IEnumerable<T>)': not all code paths return a value (Source code: public int Compare( IEnumerable<T> x, IEnumerable<T> y ) {
      if ( (StrykerTDJYDZuqS8nwmdF.MutantControl.IsActive(1572)?!(ReferenceEquals( x, y ) ):ReferenceEquals( x, y ) )) {
        return 0;
      }

      if ( (StrykerTDJYDZuqS8nwmdF.MutantControl.IsActive(1574)?!(x == null ):(StrykerTDJYDZuqS8nwmdF.MutantControl.IsActive(1573)?x != null :x == null ))) {
        return (StrykerTDJYDZuqS8nwmdF.MutantControl.IsActive(1575)?+1:-1);
      }

      if ( (StrykerTDJYDZuqS8nwmdF.MutantControl.IsActive(1577)?!(y == null ):(StrykerTDJYDZuqS8nwmdF.MutantControl.IsActive(1576)?y != null :y == null ))) {
        return 1;
      }

      using ( var xs = x.GetEnumerator() )
      using ( var ys = y.GetEnumerator() ) {
        while ( (StrykerTDJYDZuqS8nwmdF.MutantControl.IsActive(1579)?!(true ):(StrykerTDJYDZuqS8nwmdF.MutantControl.IsActive(1578)?false:true ))) {
          var xMove = xs.MoveNext();
          var yMove = ys.MoveNext();

          if ( (StrykerTDJYDZuqS8nwmdF.MutantControl.IsActive(1582)?!(xMove ^ yMove ):(StrykerTDJYDZuqS8nwmdF.MutantControl.IsActive(1581)?~(xMove ^ yMove ):(StrykerTDJYDZuqS8nwmdF.MutantControl.IsActive(1580)?xMove == yMove :xMove ^ yMove )))) {
            if ( (StrykerTDJYDZuqS8nwmdF.MutantControl.IsActive(1584)?!(!xMove ):(StrykerTDJYDZuqS8nwmdF.MutantControl.IsActive(1583)?xMove :!xMove ))) {
              return (StrykerTDJYDZuqS8nwmdF.MutantControl.IsActive(1585)?+1:-1);
            }
            return 1;
          }

          if ( (StrykerTDJYDZuqS8nwmdF.MutantControl.IsActive(1587)?!(!xMove ):(StrykerTDJYDZuqS8nwmdF.MutantControl.IsActive(1586)?xMove :!xMove ))) {
            return 0;
          }

          var cmp = _elementComparer.Compare( xs.Current, ys.Current );
          if ( (StrykerTDJYDZuqS8nwmdF.MutantControl.IsActive(1589)?!(cmp != 0 ):(StrykerTDJYDZuqS8nwmdF.MutantControl.IsActive(1588)?cmp == 0 :cmp != 0 ))) {
            return cmp;
          }
        }
      }
    })
```

**Logs**
The logs contain a bit too much info for me to share in their entirety, but the specifically affected code is:

```cs
  public class EnumerableComparer<T> : IComparer<IEnumerable<T>> {
    private readonly IComparer<T> _elementComparer;

    /// <summary>
    /// Construct comparer using default element comparer
    /// </summary>
    public EnumerableComparer() {
      _elementComparer = Comparer<T>.Default;
    }

    /// <summary>
    /// Construct comparer using specified element comparer
    /// </summary>
    public EnumerableComparer( IComparer<T> elementComparer ) {
      _elementComparer = elementComparer;
    }

    /// <inheritdoc />
    public int Compare( IEnumerable<T> x, IEnumerable<T> y ) {
      if ( ReferenceEquals( x, y ) ) {
        return 0;
      }

      if ( x == null ) {
        return -1;
      }

      if ( y == null ) {
        return 1;
      }

      using ( var xs = x.GetEnumerator() )
      using ( var ys = y.GetEnumerator() ) {
        while ( true ) {
          var xMove = xs.MoveNext();
          var yMove = ys.MoveNext();

          if ( xMove ^ yMove ) {
            if ( !xMove ) {
              return -1;
            }
            return 1;
          }

          if ( !xMove ) {
            return 0;
          }

          var cmp = _elementComparer.Compare( xs.Current, ys.Current );
          if ( cmp != 0 ) {
            return cmp;
          }
        }
      }
    }
  }
}
```

**Expected behavior**
It not telling me to report a bug :)

**Desktop (please complete the following information):**
 - OS: Windows
 - Type of project: netstd 2.0/net462 multitargeted
 - Stryker Version: beta 0.16.0

**Comment by richardwerkman** [comment] 2020-02-24 12:46
Closing as this is a duplicate of #642

**Closed by richardwerkman** 2020-02-24 12:46 UTC
Labels: bug
