### ISSUE TITLE
Stryker exits with unhandled exception: InvalidOperationException

### ISSUE THREAD

**Issue by pawelhevy** [stryker-mutator/stryker-net#1902] opened 2022-02-11 12:12 UTC
**Describe the bug**
Stryker exits with unhandled exception: InvalidOperationException for code like:
```
Action unsubscribe = () => client.SendCompleted -= handler;
```

**Logs**
```
Unhandled exception. System.InvalidOperationException: Can't extract original expression from {{return client.SendCompleted -= handler;}}
   at Stryker.Core.Instrumentation.AnonymousFunctionExpressionToBodyEngine.Revert(AnonymousFunctionExpressionSyntax node) in /_/src/Stryker.Core/Stryker.Core/Instrumentation/AnonymousFunctionExpressionToBodyEngine.cs:line 40
   at Stryker.Core.Instrumentation.BaseEngine`1.RemoveInstrumentation(SyntaxNode node) in /_/src/Stryker.Core/Stryker.Core/Instrumentation/BaseEngine.cs:line 47
   at Stryker.Core.Mutants.MutantPlacer.RemoveMutant(SyntaxNode nodeToRemove) in /_/src/Stryker.Core/Stryker.Core/Mutants/MutantPlacer.cs:line 114
   at Stryker.Core.Compiling.RollbackProcess.RemoveMutantIfStatements(SyntaxTree originalTree, IEnumerable`1 diagnosticInfo, Boolean devMode) in /_/src/Stryker.Core/Stryker.Core/Compiling/RollbackProcess.cs:line 253
   at Stryker.Core.Compiling.RollbackProcess.Start(CSharpCompilation compiler, ImmutableArray`1 diagnostics, Boolean lastAttempt, Boolean devMode) in /_/src/Stryker.Core/Stryker.Core/Compiling/RollbackProcess.cs:line 59
   at Stryker.Core.Compiling.CsharpCompilingProcess.TryCompilation(Stream ms, Stream symbolStream, CSharpCompilation compilation, EmitResult previousEmitResult, Boolean lastAttempt, Boolean devMode, Int32 retryCount) in /_/src/Stryker.Core/Stryker.Core/Compiling/CsharpCompilingProcess.cs:line 134
   at Stryker.Core.Compiling.CsharpCompilingProcess.Compile(IEnumerable`1 syntaxTrees, Stream ilStream, Stream symbolStream, Boolean devMode) in /_/src/Stryker.Core/Stryker.Core/Compiling/CsharpCompilingProcess.cs:line 81
   at Stryker.Core.MutationTest.CsharpMutationProcess.CompileMutations() in /_/src/Stryker.Core/Stryker.Core/MutationTest/CsharpMutationProcess.cs:line 74
   at Stryker.Core.MutationTest.CsharpMutationProcess.Mutate() in /_/src/Stryker.Core/Stryker.Core/MutationTest/CsharpMutationProcess.cs:line 66
   at Stryker.Core.MutationTest.MutationTestProcess.Mutate() in /_/src/Stryker.Core/Stryker.Core/MutationTest/MutationTestProcess.cs:line 116
   at Stryker.Core.Initialisation.ProjectMutator.MutateProject(StrykerOptions options, IReporter reporters) in /_/src/Stryker.Core/Stryker.Core/Initialisation/ProjectMutator.cs:line 42
   at Stryker.Core.Initialisation.ProjectOrchestrator.MutateProjects(StrykerOptions options, IReporter reporters)+MoveNext() in /_/src/Stryker.Core/Stryker.Core/Initialisation/ProjectOrchestrator.cs:line 61
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Stryker.Core.StrykerRunner.RunMutationTest(IStrykerInputs inputs, ILoggerFactory loggerFactory, IProjectOrchestrator projectOrchestrator) in /_/src/Stryker.Core/Stryker.Core/StrykerRunner.cs:line 58
   at Stryker.CLI.StrykerCli.RunStryker(IStrykerInputs inputs) in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 90
   at Stryker.CLI.StrykerCli.<>c__DisplayClass9_0.<Run>b__0() in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 65
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass143_0.<OnExecute>b__0(CancellationToken _)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Stryker.CLI.StrykerCli.Run(String[] args) in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 71
   at Stryker.CLI.Program.Main(String[] args) in /_/src/Stryker.CLI/Stryker.CLI/Program.cs:line 15
```

**Expected behavior**
Stryker does not throw unhandled exceptions

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Type of project: core
 - Framework Version: net6.0
 - Stryker Version: 1.3.1

**Additional context**
It works if I replace it by
```
Action unsubscribe = () => { client.SendCompleted -= handler; };
```
I've notice that there is not implemented case in switch statement:
![image](https://user-images.githubusercontent.com/7288991/153589344-3ee28ee6-0ce5-4a90-a472-03e3e31c74df.png)

See https://github.com/stryker-mutator/stryker-net/issues/1847#issuecomment-1036110319

**Comment by dupdob** [comment] 2022-02-11 16:22
Thanks for reporting this. I am looking into this. That is also great you ran it under debugger to get a better picture.
The `throw` statement is on purpose of course, as this situation can only happen is there is a bug somewhere **else**. As you can see, this code converts a statement body (anonymous) function back to its original expression form. In order to do that, it expects a body that looks like this `{ return <some_expression>; }` and returns `<some_expression>`.
It fails because it is asked to convert `{{ return <some_expression>; }}` (notice the extra curly braces) which it cannot do.

This could be fixed by removing those extra braces, but this happens because some other part of Stryker did not remove the injected braces.
I will add regression tests and fix this. I will update this issue as a I make progress.

**Comment by dupdob** [comment] 2022-02-12 14:32
I reproduced and analyzed this problem. It demonstrated that the mutation logic for anonymous expression is incomplete and does not properly handle assignment statement mutations (such as `+=` to `-=`). And also that roll back logic may not handle these cases well either.
I have a partial fix, working to see if I can get a better one.

**Comment by pawelhevy** [comment] 2022-02-12 18:42
I'm glad to hear that. It is very impressive that you take care of this issue so fast. Fingers are crossed!

**Comment by dupdob** [comment] 2022-02-14 22:25
I just opened a PR with the fix and regression test.

**Closed** 2022-02-16 11:23 UTC
Labels: 🐛 Bug
