### ISSUE TITLE
Stryker failure : System.InvalidOperationException: Sequence contains no elements

### ISSUE THREAD

**Issue by andreyn-msft** [stryker-mutator/stryker-net#713] opened 2019-09-11 13:04 UTC
**Describe the bug**
I don't have a clear enough description, but in Azure DevOps Stryker constantly fails on the "analyzing project" step and exits with code 1. May be I am missing something obvious.

**Logs**
The tool is executed in Azure DevOps, so the log is copied from the step logs.
[stryker-log.log](https://github.com/stryker-mutator/stryker-net/files/3600878/stryker-log.log)

**Expected behavior**
Analyze the project and run mutation tests.

**Desktop (please complete the following information):**
 - Windows nodes in Azure DevOps
 - framework
 - 4.6
 - 0.13.0 (beta)

**Additional context**

**Comment by richardwerkman** [comment] 2019-09-11 13:10
Thanks for submitting this issue! Does this behaviour only occur on Azure Devops? It looks like a dependency of ours (buildalyzer) cannot open your project file `CoreTests\CoreTests.csproj`. 

I'm curious if this happens too if you run stryker locally.

**Comment by Mobrockers** [comment] 2019-09-11 13:12
It looks like we are failing to read your test project file for some reason. Does this only happen on azure devops? Could you try it locally and use -f to produce the logfile?

Could you also perhaps share the project file with us?

**Comment by andreyns** [comment] 2019-09-11 14:14
yes, it fails in Azure Devops only. here is the log collected locally
[log-20190911.txt](https://github.com/stryker-mutator/stryker-net/files/3601205/log-20190911.txt)

unfortunately, I can't share the project :-\

**Comment by andreyns** [comment] 2019-09-11 14:17
and here is the project file with tests
[CoreTests.csproj.txt](https://github.com/stryker-mutator/stryker-net/files/3601220/CoreTests.csproj.txt)

**Comment by richardwerkman** [comment] 2019-09-11 14:58
One difference I can think of is the msbuild version. There might be a version installed on DevOps that is not compatible with buildalyzer. 

Unfortunately we don't log the msbuild version before stryker crashes... So I can't compare the versions.

**Comment by andreyns** [comment] 2019-09-11 17:39
is there any script or a command I can execute locally and on the agent to collect additional details?

**Comment by Mobrockers** [comment] 2019-09-11 19:05
If you add -f to the stryker run in your pipeline you could use publish pipeline artifact to publish the stryker logs to your build pipeline. You can then download them and send them to us.

Other than that I'm not sure yet. We are failing here:

https://github.com/stryker-mutator/stryker-net/blob/ccebdeecb0020f0a9010db2960c789a45cc783db/src/Stryker.Core/Stryker.Core/Initialisation/ProjectFileReader.cs#L58

Which to me indicates that for some reason we are unable to build your targetframework(s) using buildalyzer.

I'll try to repro using your csproj. Could you perhaps share the solutionfile and project under test projectfile as well? You can remove any sensitive information and I don't think I need any source files.

Also, which vm images are you using in your hosted pipelines? Just windows-latest or some other version? And are they the normal versions everyone else uses or are they some microsoft internal agents?

**Comment by andreyns** [comment] 2019-09-13 07:16
Here is the log from the agent:
[log-20190913.txt](https://github.com/stryker-mutator/stryker-net/files/3608736/log-20190913.txt)

the solution file:
AsyncMediaShared.sln.txt](https://github.com/stryker-mutator/stryker-net/files/3608770/AsyncMediaShared.sln.txt)

the project I want to test:
[Core.csproj.txt](https://github.com/stryker-mutator/stryker-net/files/3608779/Core.csproj.txt)

The agents are internal, most likely with the latest Windows and pre-installed VS2017 and Azure SDK

**Comment by Mobrockers** [comment] 2019-09-13 15:33
I'm not seeing anything at all suspicious about those project files, SDK style and using package reference is pretty much ideal for buildalyzer and stryker (short of being dotnet core). Have you tried it with any other projects and/or agents?

**Comment by andreyns** [comment] 2019-09-13 16:42
yeah, I did. it fails with the same exception:

[07:15:03 ERR] An error occurred during the mutation test run 
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)

**Comment by Mobrockers** [comment] 2019-09-23 18:44
Would it be possible to get access to the build agent or perhaps a list of all software and versions so I can try to reproduce? Software versions for windows, visual studio, msbuild, nuget and dotnet (core) installed on the system as a minimum to try to rebuild the agent on a vm.

**Comment by Mobrockers** [comment] 2019-11-29 15:42
Closing until repro is available

**Comment by samvandenbossche** [comment] 2020-04-20 08:49
Is there any progress on this issue? I'm having the exact same behaviour

**Comment by richardwerkman** [comment] 2020-04-20 10:59
@samvandenbossche Do you have a reproduction project that we can use to analyse the problem? With the current info we cannot research what went wrong.

**Comment by samvandenbossche** [comment] 2020-04-20 13:12
I'm afraid not because it's against employer guidelines. 
it's a mulpti-project solution  
All projects have target framework 4.7.2 and are using the new Dependency format. 
MsBuild version 4.8.3752.0

**Comment by Mobrockers** [comment] 2020-04-21 05:50
Could you perhaps create a reproduction using your current project as a template? Just remove anything that's not necessary to produce the failure, anything proprietary. I know that might be a lot of work but if you can't help us create a reproduction there's unfortunately nothing we can do to investigate.

**Comment by samvandenbossche** [comment] 2020-04-21 11:29
I'll give it a try

**Comment by eNeRGy164** [comment] 2020-10-23 16:07
If the builds were running under Linux, this issue might have fixed it: https://github.com/daveaglick/Buildalyzer/pull/142
This is part of Buildalyzer 3.0.1

**Comment by Mobrockers** [comment] 2020-10-23 16:35
Thanks for the ping @eNeRGy164.

I don't think they were running on linux as they were all dotnet framework projects as far as I can tell but I'm gonna go and close this issue anyway since there hasn't been any activity for a while.

**Closed by Mobrockers** 2020-10-23 16:35 UTC
Labels: bug, repro needed
