### ISSUE TITLE
Exclude folder path from mutation in stryker-config

### ISSUE THREAD

**Issue by gentcod** [stryker-mutator/stryker-net#2795] opened 2023-12-12 05:15 UTC
I am trying to exclude DB migrations from mutation.

The code for the DB migrations is auto generated by Entity Framework Core and it makes no sense to include them in the mutation as there are a lot of hard coded string values. It gets the mutants that are not covered.

This is a sample of code generated that needs to be excluded:
`
migrationBuilder.CreateTable(
                name: "RecipeRatings",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    RecipeId = table.Column<int>(type: "INTEGER", nullable: false),
                    RatingNum = table.Column<int>(type: "INTEGER", nullable: false),
                    Comment = table.Column<string>(type: "TEXT", nullable: true)
                },
`

**Comment by rouke-broersma** [comment] 2023-12-12 05:42
Did you try the mutate option?

**Comment by gentcod** [comment] 2023-12-12 05:51
I excluded the methods using "ignore-methods" but the strings and boolean values are being highlighted for mutation, categorized under No Coverage

I have about 100+ mutants being highlighted from just that file.

**Comment by rouke-broersma** [comment] 2023-12-12 06:49
Ignore methods is not the same as mutate. Try the mutate option. https://stryker-mutator.io/docs/stryker-net/configuration/#mutate-glob

**Comment by dupdob** [comment] 2023-12-12 08:26
I am not familiar with EF inner workings, but Stryker normally does not mutate generated code.
To be specific, it does not mutate build time generated code, plus a bunch of well known patterns.

**Comment by gentcod** [comment] 2023-12-12 09:09
It doesn't but instead of ignoring the contents, it categorizes it as mutants that are not covered.

Not Covered mutants fall are regarded as survived mutants, so still affecting the mutation score

I noticed it ignored 2 other files in the same directory though; EF Core generates 3 files when a migration is initialized.

**Comment by rouke-broersma** [comment] 2023-12-12 09:23
> I am not familiar with EF inner workings, but Stryker normally does not mutate generated code.
> To be specific, it does not mutate build time generated code, plus a bunch of well known patterns.

Iirc ef doesn't consider it generated code because you should always manually check and modify migrations, so they refuse to place the generated code attribute.

**Comment by rouke-broersma** [comment] 2023-12-12 09:25
> It doesn't but instead of ignoring the contents, it categorizes it as mutants that are not covered.
> 
> Not Covered mutants fall are regarded as survived mutants, so still affecting the mutation score
> 
> I noticed it ignored 2 other files in the same directory though; EF Core generates 3 files when a migration is initialized.

It should be marked as ignored when excluding using the mutate option. Could you share your full configuration or your debug log file?

Are you using since or baseline?

**Comment by gentcod** [comment] 2023-12-12 09:28
> > I am not familiar with EF inner workings, but Stryker normally does not mutate generated code.
> > To be specific, it does not mutate build time generated code, plus a bunch of well known patterns.
> 
> Iirc ef doesn't consider it generated code because you should always manually check and modify migrations, so they refuse to place the generated code attribute. 

Well, yeah I understand but there are still a lot of hard coded values that could be mutated.

**Comment by gentcod** [comment] 2023-12-12 09:34
This is the configuration I have used so far:

{
  "stryker-config":
   {
       "ignore-methods": [
         "*migrationBuilder.CreateTable",
         "*migrationBuilder.CreateIndex",
         "*migrationBuilder.DropTable",
         "*Column",
         "*Annotation",
         "*PrimaryKey",
         "*ForeignKey"
       ],
       "thresholds": {
         "high": 80,
         "low": 60,
         "break": 0
       },
       "reporters": [
         "progress",
         "html",
         "cleartext"
       ]
   }
}`
`

**Comment by richardwerkman** [comment] 2023-12-13 15:35
@gentcod The option you are using won't work in this case. `ignore-methods` will only ignore the _invocations_ of those methods. Not the _declarations_. So the behaviour you're seeing is by design. In this case you could use stryker comments or the mutate option.

See: https://stryker-mutator.io/docs/stryker-net/ignore-mutations/ for an extensive guide on how to ignore mutations.

**Comment by gentcod** [comment] 2023-12-13 21:16
@richardwerkman oh I get but in cases where there are strings in other test suites, that implies that they would be overlooked unless there is a way for me to ignore specific strings. If there is, please do let me know, thank you.

**Comment by gentcod** [comment] 2023-12-13 21:52
I read the documentation and saw `exclude-mutation` referenced on the page for `ignore-mutations` docs but it's not available on the configuration page.

**Comment by rouke-broersma** [comment] 2023-12-14 05:47
> I read the documentation and saw `exclude-mutation` referenced on the page for `ignore-mutations` docs but it's not available on the configuration page.

Could you link to these docs?

**Comment by gentcod** [comment] 2023-12-14 05:50
https://stryker-mutator.io/docs/stryker-net/mutations/

**Comment by rouke-broersma** [comment] 2024-06-07 14:30
I'm updating those docs, it should not be called exclude-mutations.

As for your original issue, the method to use to ignore those declarations is to use stryker comments. See: https://stryker-mutator.io/docs/stryker-net/ignore-mutations/#stryker-comments

**Closed by rouke-broersma** 2024-06-07 14:30 UTC
Labels: 🚀 Feature request
