### ISSUE TITLE
Mutations not found

### ISSUE THREAD

**Issue by psfinaki** [stryker-mutator/stryker-net#1957] opened 2022-03-09 16:07 UTC
**Describe the bug**
After updating from 1.3.1 to 1.4.2, I'm getting these errors:
<img width="598" alt="image" src="https://user-images.githubusercontent.com/5451366/157478302-d0e5e1fb-128d-492e-ad3f-1f4aee008d67.png">

This affects mutation score.

**Logs**
Log file contains too much NDA and I cannot easily understand how to regex it out :D But generally, this is how things look like there:
<img width="857" alt="image" src="https://user-images.githubusercontent.com/5451366/157480185-51342ceb-953b-48f0-8962-76d7ed2f03dd.png">
<img width="736" alt="image" src="https://user-images.githubusercontent.com/5451366/157480294-73832a37-1613-4490-943e-7987441f44be.png">

**Expected behavior**
Mutations are found?

**Desktop (please complete the following information):**
 - OS: Windows
 - Type of project: .NET Core
 - Framework Version: .NET 6
 - Stryker Version: **1.4.2**

**Additional context**
If you don't have any ideas, I can try redacting the logs are creating some repro. But I thought you might have some ideas since it's clear what commits to look into.

**Comment by richardwerkman** [comment] 2022-03-09 16:14
My first thought is that we somehow don't place the mutant id in the AST when placing the mutation. But I don't have time today to look into this 😞

**Comment by dupdob** [comment] 2022-03-09 18:51
There have been a change in the roll back logic introduced in V1.4 which induced a regression: Stryker sometimes attempted to remove some mutations more than once, which triggered an NRE. That has been fixed in V1.4.1. Judging on the log, there is no real issue, just logging noise:
1. The errors do not refer to an actual mutations but to some helper logic (indicated by the `-1` identifier). Sadly the log message is misleading.
2. The discrepancy you see in mutation score is likely due to the reduction of safe mode triggers in V1.4. Safe mode means Stryker removes every mutant from a method (or accessor/lambda...) which implies those are no longer mutation tested. So with V 1.4 you should have more mutants to run and less in compile error.

This comment is only based on you log and the knowledge of the code base. I will  look into this to confirm this diagnostic.

**Comment by psfinaki** [comment] 2022-03-09 20:35
Thanks @dupdob for looking into that. Well from what I understood (quote from a dev who saw that: "Peter, before the stryker update the following were not mutants, now they are 😨"), that seems to be the case...

Noise is one thing but Stryker behavioral compatibility is another... do you think there is any way to get the same score in this version by modifying the config?

I'm asking because we run the same Stryker config against 130+ projects, lock in mutation scores, have a PR gate controlling them and also formally "stage" projects partially based on this score, like dev/beta/preview/etc which in turn defines terms of usage. So if the answer to the previous question is no, I'll basically have to simulate this run on the new Stryker version, adjust the scores everywhere and probably also add some tests to a bunch of projects I have no knowledge about or "demote" them which is much bureaucracy.

So it's just for you a glimpse on how Stryker can be used in "big corp" and what responsibility we carry here :D E.g. block mutations were added in an ideal manner as they could be trivially turned off in the config to not "disrupt the business".

**Comment by dupdob** [comment] 2022-03-09 21:39
After reviewing the code, the conclusion is that these messages must be viewed as noise; at the very least they should not be reported as an error. Clean up is due.

**Comment by dupdob** [comment] 2022-03-09 22:29
Regarding the score variation across version, I understand your problem and I suggest you open an issue on that.
I am not sure what the solution would be, as we constantly try to improve the efficiency and coverage of Stryker.Net.
As such, the number of viable mutations naturally increases as the project matures. 
Below are a few heuristics to keep in mind, but let me digress a bit to discuss about 'Safe mode'.
Generated mutations may trigger build error; Stryker remove those. But when Stryker cannot identify which mutations is source of a build error, it triggers 'safe mode', i.e it removes every mutations from the member (method, property, lambda...) in error and mark them as 'compile error', including mutations that were perfectly ok and could have been tested.
1. A new mutator obviously result in more mutations being generated. This changes the score, but you can chose to disable any mutator.
2. As long as it is cheap to test for, Stryker discards mutations that would result in a compilation error. When we improve on that, this does not change the score but results in less mutations being generated.
3. We aim at eliminating 'safe mode' triggers, as those reduce Stryker efficiency. Then, the total number of mutations does not change, but we have (a lot) less compile errors. This may change the score as a bunch of erroneously discarded mutations is now properly tested.
4. Mutators may have bugs resulting in having less mutations than possible. This is a rare occurence.
5. The syntax parsing logic may have bugs or shortcomings. New syntax constructs are often problematic. Those also result in less mutations being generated (sometimes those lead to Stryker not working at all).

Situations 3,4 and 5 are BUGS and means Stryker FAILS to mutate part of the code, rendering it ineffective for part of the code, which could lead to a false sense of security for users (as a side note: mutation coverage must not be seen as a strong quality metric). As such, I don't think those should be configurable in the general case.

As a last word, please bear in mind I am not a member of the core team and only voicing my opinion here. They may have a different view than mine, hence my suggestion for a dedicated issue.

As for the original problem, I will open a PR soon for a fix, but I do not think this mandates an patch release.

**Comment by rouke-broersma** [comment] 2022-03-10 09:46
@psfinaki

New mutations are always minor or major versions bumps so we don't inconvenience our users too much, however we don't maintain any previous versions and we do not backport fixes to older minor or major versions. This means that if you hit a bug you may have to upgrade to a newer version that includes new mutations as well. I understand that this can be a big problem for using stryker in a corporate environment but we do not have the bandwidth to support backporting fixes.

In this case however we did not actually introduce any new mutations. As @dupdob said we fixed a bug that caused mutations to be incorrectly marked as compile errors. This does increase your mutation count unexpectedly, but I do not feel that a bugfix should be a minor or major version change. The previous result you were depending on was incorrect, which means work for you and I can see why that created pushback, but ultimately it is something you wish you had caught earlier and the way to deal with this, if you don't currently have the capacity to fix it, is to lower your accepted mutation score.

I appreciate this feedback on how you guys use stryker and I can clearly see the pain, but I am not sure how we could solve this for you. How would you like to see us deal with bugfixes that potentially affect the number of mutations to test?

**Comment by psfinaki** [comment] 2022-03-10 10:49
@dupdob @rouke-broersma 

Thanks for the detailed responses! This now makes much more sense. Also nice to get some tips about Safe Mode, I never looked into that deeply. I hope you didn't see my post as any kind of angry rant, I just wanted to give some context and call for some discussion :) (which seems to be happening)

I understand there's no capacity to backport stuff across versions. Also, I never saw Stryker in the light that mutation score can change _naturally_ with general improvements and bugfixes to the engine. But actually this is totally reasonable and it's also fair that eventually this is what we want as consumers.

Speaking of pains, looks like this particular thing is not such a big hit, the pain of flaky tests everywhere is much harder anyway :D Also, I'm kind of proud to say that of 130+ projects more than 70% are rather simple and have 100% mutation coverage and the tests seem to handle the new mutants in a smooth manner. But yes there are several projects with complex logic and complex testing and those are affected I think.

--- 

Now as for what we can change... I think we can change the rhetoric here :) Not all bugfixes are created equal and therefore you don't need to be equally humble about them. If some change breaks what used to be working before then okay that's a bug and a bugfix is coming. But if the change addresses something that was never really working (or not working for a loooooong time) then from the customer's perspective it's rather a feature/enhancement/improvement i.e. something good.

Therefore I think changes of that latter category deserve more attention than just a bullet point in the list of bugfixes. Call it what you want but it would be good to emphasize that **this can affect your mutation scores**. Ideally, if there are some clear cases when this might happen - can be likely inspired by tests - that's also worth noting down.

If this makes sense for you, we can use this case as an exercise. If you guys are going to remove this noise, I would be very grateful if this actually gets released and maybe briefly described in such manner in release notes so that I could point people there :)

**Comment by rouke-broersma** [comment] 2022-03-10 11:08
I can certainly agree that it would be good bedside manners to tell users in the changelog that a fix can have an impact on the mutation score!

**Comment by dupdob** [comment] 2022-03-10 16:29
agree. I think opening a feature request around this could be interesting: what can/should be done on Stryker when using as a quality gate (on top of the existing kill threshold option).
Regarding signaling mutation score impact, I am contemplating using a (dedicated) version number that could be displayed in the banner and the reports to track this across releases. With a specific semantic, such as: V L.M.b
1. (L) (Major): a change implies a deep change in the mutation logic, rendering score comparison difficult. For example : Stryker supports mutating fields, or ressources
2. M (minor): a change implies Stryker generates more mutants, either by simple efficiency (better parsing) or via new mutators. Scores are expected to change but not in a dramatic fashion
3. b (patch): bug fix, number of generated mutants is the same, but more are tested and/or testing results are more accurate (eg. we fix a coverage related bug that lead to false survivors). Score may change, depending on the type of project, but change should be marginal

**Comment by psfinaki** [comment] 2022-03-11 10:48
> what can/should be done on Stryker when using as a quality gate

Didn't fully get this :(

In regard to versioning, I like the idea! However, for the patch
> Score may change, depending on the type of project, but change should be marginal

this might be a bit of a stretch. I would really leave the patches for things like fixing reporters not working :)

**Comment by dupdob** [comment] 2022-03-11 15:25
Sorry for the lingo: 
> Stryker as a quality gate
Having a minimal Stryker Mutator's score for the build to pass.
> Versioning
The idea is to have a supplemental version number dedicated to keeping track of the evolution of mutation logic. Using the main version number for this would be detrimental to both uses

**Comment by rouke-broersma** [comment] 2022-03-11 15:38
My plan is to eventually split off the mutation engine as a separate project from the rest of stryker, at that point we can give it it's own dedicated version number (and nuget package etc). I have future plans for this mutation engine package that necessitate this split. But, this is all distant future plans so don't expect anything soon.

**Comment by dupdob** [comment] 2022-03-13 14:47
PR #1964 fixes the spurious logs

**Closed** 2022-03-13 20:17 UTC
Labels: 🐛 Bug

**Comment by psfinaki** [comment] 2022-03-14 15:27
Thanks for addressing this @dupdob!

@rouke-broersma, as I mentioned earlier, I'd still appreciate a release for that - also because of this ExcludeFromCodeCoverage fix :)

**Comment by rouke-broersma** [comment] 2022-03-15 08:10
release is rolling

**Comment by psfinaki** [comment] 2022-03-15 14:36
Thanks a lot!
