### ISSUE TITLE
Stryker does not use modified output path

### ISSUE THREAD

**Issue by grishnak666** [stryker-mutator/stryker-net#759] opened 2019-10-04 09:55 UTC
**Describe the bug**
I have a C# project targeted to .net framework 4.7.2. The solution contains a library and a unit test project. In the .csproj path of both the library and the test project i have set 
`<OutputPath>..\Build\bin\</OutputPath>`
and Stryker runs fine.

When i change it to
`<OutputPath>..\Build\bin\$(SolutionName)\</OutputPath>`
and run Stryker i receive the error
`The test project binaries could not be found at D:\***\MutationTests\**Build\bin\**MyLib.UnitTests.dll`

So, Stryker seems to not use the solution name specified in the output path. And yes, the project compiles and the binaries can be found in the solution named subfolder.

**Logs**

> [11:45:52 INF] The project D:\---\MutationTests\MyLib\MyLib.csproj will be mutated
[11:45:53 INF] Started initial build using msbuild.exe
[11:45:54 INF] Initial build successful
[11:45:57 ERR] An error occurred during the mutation test run
System.ApplicationException: The test project binaries could not be found at D:\---\MutationTests\Build\bin\MyLib.UnitTests.dll, exiting...
   at Stryker.Core.TestRunners.VsTest.VsTestRunner.InitializeVsTestConsole() in d:\a\1\s\src\Stryker.Core\Stryker.Core\TestRunners\VsTest\VsTestRunner.cs:line 417
   at Stryker.Core.TestRunners.VsTest.VsTestRunner..ctor(StrykerOptions options, OptimizationFlags flags, ProjectInfo projectInfo, ICollection`1 testCasesDiscovered, TestCoverageInfos mappingInfos, IFileSystem fileSystem, IVsTestHelper helper, ILogger logger, IVsTestConsoleWrapper wrapper, Func`3 hostBuilder) in d:\a\1\s\src\Stryker.Core\Stryker.Core\TestRunners\VsTest\VsTestRunner.cs:line 82
   at Stryker.Core.TestRunners.VsTest.VsTestRunnerPool..ctor(StrykerOptions options, OptimizationFlags flags, ProjectInfo projectInfo) in d:\a\1\s\src\Stryker.Core\Stryker.Core\TestRunners\VsTest\VsTestRunnerPool.cs:line 32
   at Stryker.Core.TestRunners.TestRunnerFactory.Create(StrykerOptions options, OptimizationFlags flags, ProjectInfo projectInfo) in d:\a\1\s\src\Stryker.Core\Stryker.Core\TestRunners\TestRunnerFactory.cs:line 31
   at Stryker.Core.Initialisation.InitialisationProcess.Initialize(StrykerOptions options) in d:\a\1\s\src\Stryker.Core\Stryker.Core\Initialisation\InitialisationProcess.cs:line 48
   at Stryker.Core.StrykerRunner.RunMutationTest(StrykerOptions options, IEnumerable`1 initialLogMessages) in d:\a\1\s\src\Stryker.Core\Stryker.Core\StrykerRunner.cs:line 74
[11:45:57 INF] Time Elapsed 00:00:07.5529038

**Expected behavior**
Stryker should use the configuration configured in the project files.

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Type of project [C#, .NET Framework 4.7.2]
 - Framework Version [4.7.2]
 - Stryker Version [0.13.0]

**Additional context**
None

**Comment by Mobrockers** [comment] 2019-10-04 10:05
Thank you for your report. This seems to be a duplicate of #639  Can you confirm?

**Comment by grishnak666** [comment] 2019-10-04 10:12
> Thank you for your report. This seems to be a duplicate of #639 Can you confirm?

Not sure which bug was fixed with #639.

**Comment by Mobrockers** [comment] 2019-10-04 10:17
Oops sorry I meant #638

**Comment by grishnak666** [comment] 2019-10-04 10:58
Yes, #638 describes the same problem.

**Comment by Mobrockers** [comment] 2019-10-04 11:07
If you don't mind I'll close this issue as duplicate then. Feel free to add any additional info to the other issue. Also if you think you might be able to fix the issue yourself we are happy to accept PR's :)

**Closed by Mobrockers** 2019-10-04 11:07 UTC
Labels: bug
