### ISSUE TITLE
[Regression] NRE in Stryker 1.4.0

### ISSUE THREAD

**Issue by jfheins** [stryker-mutator/stryker-net#1937] opened 2022-03-03 07:39 UTC
**Describe the bug**
Stryket.net 1.4.0 crashes unexpectedly.

**Logs**
I am not sure how much project data is contained in the log, can I mail it?

**Expected behavior**
I expect stryker not to crash.
I tested Stryker.net 1.3.1 on Tuesday and it worked fine but (with the same code of course) but version 1.4.0 does not work any more.

**Desktop (please complete the following information):**
 - OS: ubuntu-20.04
 - Type of project asp.net core on .net 6
 - Framework Version .net 6
 - Stryker Version 1.4.0

**Additional context**

```
[20:53:48 INF] Initial testrun started.
[20:58:33 WRN] Initial test run encounter a unexpected test case (mytestcase(null,7ec6a09b-ef05-4ba0-8fc4-d4ab8241b506,False,"123")), mutation tests may be inaccurate. Disable coverage analysis if your have doubts.
[20:58:33 WRN] Initial test run encounter a unexpected test case (mytestcase(00000000-0000-0000-0000-000000000000,a6e2f34d-dcd2-47f3-96ea-0f6be47212c5,False,"234")), mutation tests may be inaccurate. Disable coverage analysis if your have doubts.
[20:58:33 WRN] Initial test run encounter a unexpected test case (mytestcase(15909311-1dc0-495a-b0f5-a938faae7e5c,c312cf38-aa26-4560-a44e-97810cd6d0e9,False,"345")), mutation tests may be inaccurate. Disable coverage analysis if your have doubts.
[20:58:33 WRN] Initial test run encounter a unexpected test case (mytestcase(98c42e5d-0a76-443a-8825-57b9130d6a3c,98c42e5d-0a76-443a-8825-57b9130d6a3c,True,"456")), mutation tests may be inaccurate. Disable coverage analysis if your have doubts.
[20:58:40 ERR] Mutation not found, this should not happen
[20:58:42 ERR] Mutation not found, this should not happen
[20:58:42 ERR] Mutation not found, this should not happen
[20:58:42 ERR] Mutation not found, this should not happen
[20:58:42 ERR] Mutation not found, this should not happen
[20:58:44 WRN] Stryker.NET encountered an compile error in /home/vsts/work/1/s/Backend/MyProject/Ats.MyProject.Logic/Processing/Services/Other/MyLogicAssigner.cs (at 255:19) with message: Use of unassigned local variable 'assignments' (Source code: assignments)
[20:58:44 WRN] Stryker.NET encountered an compile error in /home/vsts/work/1/s/Backend/MyProject/Ats.MyProject.Logic/Processing/Services/Other/MyLogicTraceActionService.cs (at 456:56) with message: Use of unassigned local variable 'entity' (Source code: entity)
[20:58:44 WRN] Stryker.NET encountered an compile error in /home/vsts/work/1/s/Backend/MyProject/Ats.MyProject.Logic/Processing/Services/SpecialLogic/DistributionService.cs (at 281:16) with message: Use of unassigned local variable 'step' (Source code: step)
[20:58:44 WRN] Stryker.NET encountered an compile error in /home/vsts/work/1/s/Backend/MyProject/Ats.MyProject.Logic/Processing/Services/SpecialLogic/DistributionService.cs (at 284:16) with message: Use of unassigned local variable 'traceSource' (Source code: traceSource)
[20:58:44 INF] Time Elapsed 00:05:33.6714366
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Stryker.Core.Mutants.MutantPlacer.RemoveMutant(SyntaxNode nodeToRemove)
   at Stryker.Core.Compiling.RollbackProcess.RemoveMutantIfStatements(SyntaxTree originalTree, IEnumerable`1 diagnosticInfo, Boolean devMode)
   at Stryker.Core.Compiling.RollbackProcess.Start(CSharpCompilation compiler, ImmutableArray`1 diagnostics, Boolean lastAttempt, Boolean devMode)
   at Stryker.Core.Compiling.CsharpCompilingProcess.TryCompilation(Stream ms, Stream symbolStream, CSharpCompilation compilation, EmitResult previousEmitResult, Boolean lastAttempt, Boolean devMode, Int32 retryCount)
   at Stryker.Core.Compiling.CsharpCompilingProcess.Compile(IEnumerable`1 syntaxTrees, Stream ilStream, Stream symbolStream, Boolean devMode)
   at Stryker.Core.MutationTest.CsharpMutationProcess.CompileMutations()
   at Stryker.Core.MutationTest.CsharpMutationProcess.Mutate()
   at Stryker.Core.MutationTest.MutationTestProcess.Mutate()
   at Stryker.Core.Initialisation.ProjectMutator.MutateProject(StrykerOptions options, IReporter reporters)
   at Stryker.Core.Initialisation.ProjectOrchestrator.MutateProjects(StrykerOptions options, IReporter reporters)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Stryker.Core.StrykerRunner.RunMutationTest(IStrykerInputs inputs, ILoggerFactory loggerFactory, IProjectOrchestrator projectOrchestrator)
   at Stryker.CLI.StrykerCli.RunStryker(IStrykerInputs inputs) in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 90
   at Stryker.CLI.StrykerCli.<>c__DisplayClass9_0.<Run>b__0() in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 65
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass143_0.<OnExecute>b__0(CancellationToken _)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Stryker.CLI.StrykerCli.Run(String[] args) in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 71
   at Stryker.CLI.Program.Main(String[] args) in /_/src/Stryker.CLI/Stryker.CLI/Program.cs:line 15
##[error]Bash exited with code '134'.
```

**Comment by jfheins** [comment] 2022-03-03 10:49
Hi :-)
No, Stryker 1.3.1 did report the warnings ("Initial test run encounter a unexpected test case") but did not error out.
I am not comfortable sharing the code publicly but I can provide some source in Slack. (I have already wrote to Richard Werkman)

Example pattern would be:
```
List<int> list;
if (a)
{
  list = new List<int>();
}
else
{
  list = new List<int>();
}
```
so C# is smart enough to see that the variable is always assigned, but if one block is deleted, it will have a compile error.

**Comment by dupdob** [comment] 2022-03-03 14:41
Thanks, this is indeed sufficient to reproduce the crash. I am analyzing the issue

**Comment by dupdob** [comment] 2022-03-03 15:16
Analysis is done
# Analysis
A regression has been introduced alongside the improved roll back logic, leading Stryker to try to remove some mutations more than once. This leads to a NRE has it cannot find the mutation that has already been removed.

# Probable cause
The design of the rollback has been revised alongside the implementation of the block roll back logic (two different branches). There must have been a merge accident.

# Fix
Reintroduce the proper logic.

I will be working on the fix today or tomorrow.

**Comment by richardwerkman** [comment] 2022-03-03 15:26
Thanks for looking into this @dupdob. If you don't have time I certainly have time tomorrow.

**Comment by mumby0168** [comment] 2022-03-03 15:51
Yeah I am seeing this as well, great to see there is a fix incoming 😃

**Comment by dupdob** [comment] 2022-03-03 18:35
Update:
I have what looks to be a fix, but I am still lacking a regression test. It turns out the example @jfheins gave me raise the problem due a compilation error (I failed to define `a`).
I will open a PR has soon as I have a proper regression test.
Note that in any case, this may not fully fix the problem as I do not have a real world reproducing scenario

**Comment by dupdob** [comment] 2022-03-03 19:00
I found out reproducing code, so I have a proper  regression test.
I just opened a PR with the fix.

**Comment by richardwerkman** [comment] 2022-03-04 16:09
This should be fixed with our release today

**Closed by richardwerkman** 2022-03-04 16:09 UTC
Labels: 🐛 Bug
