### ISSUE TITLE
Cannot kill binary expression mutant

### ISSUE THREAD

**Issue by alexbunardzic** [stryker-mutator/stryker-net#441] opened 2019-04-04 19:12 UTC
I have the following conditional statement in my code:

if(x > y)

Stryker.net mutates it to:

if(x >= y) and the unit test fails to kill it.

When I modify the original condition to:

if(x >= y) Stryker mutates it back to if(x > y) and the unit test fails to kill it.

So it seems to be going in circles. How to kill that mutant?

**Comment by dupdob** [comment] 2019-04-04 19:18
could please provide the full function?

**Comment by Mobrockers** [comment] 2019-04-04 19:48
Could you provide the unit test you think should be covering that statement as well? Since you say you changed the source code rather than the unit test it would be possible that your unit test doesn't actually cover either case.

**Comment by alexbunardzic** [comment] 2019-04-04 22:36
Here is the implemented code:

        public double CalculateAdmissionPrice(int age) {
            var price = 0.0;
            if(age >= 18) {
              price = 50;
            } else if(age <= 18) {
              price = 25;
            } else {
                price = 0;
            }
            return price;
        }

Here is the unit test:

        [Fact]
        public void GivenOneAdultCalculatePrice()
        {
            var expected = 50.00;
            var calculator = new PriceCalculator();
            var actual = calculator.CalculateAdmissionPrice(35);
            Assert.Equal(expected, actual);
        }

Here is Stryker output:

All mutants have been tested, and your mutation score has been calculated
- \App5 [1/4 (25.00 %)]
--- PriceCalculator.cs [1/4 (25.00 %)]
[Killed] Binary expression mutation on line 9: 'age >= 18' ==> 'age < 18'
[Survived] Binary expression mutation on line 9: 'age >= 18' ==> 'age > 18'
[Survived] Binary expression mutation on line 11: 'age <= 18' ==> 'age > 18'
[Survived] Binary expression mutation on line 11: 'age <= 18' ==> 'age < 18'
[15:36:02 INF] Time Elapsed 00:00:11.9753304

**Comment by dupdob** [comment] 2019-04-05 04:42
thanks for providing the source code and the test.
To kill another mutant, **you should add a test for an age of 18** (to be confirmed, see below why it may also be 17 or 19).
To kill the remaining two, **you need to modify the source code**.

When I read the code, I realise that 18 is an ambiguous age, because it works both for age >= 18 **and** age<=18. From a practical point of view, the result will be 50.0, as it is the first condition checked.
But there is also the strangeness of the third path, where you return 0.0.
From a logical perspective, someone is either less than 18 years old or at least 18 years old. There is no third situation.
So, from my point of view, the code should be:
```csharp
public double CalculateAdmissionPrice(int age) {
    var price = 50.0;

    if(age < 18) {
      price = 25;
    } 
    return price;
}
```

Which can also be simplified down to:
```csharp
public double CalculateAdmissionPrice(int age) {
    return age < 18 ? 25.0 : 50.0;
}
```
Based on what you presented, of course

**Comment by richardwerkman** [comment] 2019-04-05 06:24
Dubdop has covered this already very well. It seems your attempt to kill the mutant failed because you changed the source code and not your tests. To be clear, these are the steps when you encounter a survived mutant:
- Check if the mutated code is correct
- If it is correct, add a test case for it, or rewrite your tests.
- If it is incorrect, remove or refactor the mutated code.
- Rerun stryker and see if the mutant is now killed, if not start at step 1 again.

If you do this for every survived mutant Stryker.NET finds your test quality should improve greatly.

Since this issue seems unrelated to Stryker.NET itself I will close this issue :+1:

**Closed by richardwerkman** 2019-04-05 06:24 UTC

**Comment by alexbunardzic** [comment] 2019-04-05 16:07
Thanks. What if it's not a binary choice, but we have several tiers. For example, if age < 5 price=0, if age >= 5 and age < 18 price = 25, if age >= 18 and age < 65 price= 50, if age >=65 price = 30?

**Comment by Mobrockers** [comment] 2019-04-05 16:10
Add unit tests for all your edge cases, and the mutants should be killed. The purpose of mutation testing is to see if you have exhausted all possible code paths so the fix for unkilled mutants is almost always to add unit tests or fix problems in existing unit tests. The only reason to edit source code is if examining the non-killed mutant shows you that your code has some business logic flaw.

**Comment by alexbunardzic** [comment] 2019-04-05 19:14
Thanks for your kind and gentle guidance :) Being relatively new to Stryker, I really appreciate your expertise!

**Comment by Mobrockers** [comment] 2019-04-05 19:17
You can read more about mutation testing here if you haven't read it already: https://stryker-mutator.io

**Comment by alexbunardzic** [comment] 2019-04-05 19:29
Not sure where to ask this, but what are the plans to add Block Statement mutation to Stryker.NET? Not having Block Statement mutation is the only thing holding it back from being the de facto mutating test framework for .NET

**Comment by Mobrockers** [comment] 2019-04-05 19:34
See #208

We prioritized dotnet framework support first basically. We have that now so now we can focus on other features.

>  Not having Block Statement mutation is the only thing holding it back from being the de facto mutating test framework for .NET

What framework would you say fills that role right now? :)

**Comment by alexbunardzic** [comment] 2019-04-05 19:48
Stryker.NET is the only serious contestant at the moment. But what we really need to cement it is the Block Statement.

**Comment by richardwerkman** [comment] 2019-04-08 07:05
@alexbunardzic thank you for your input! The block mutator will come soon 👍 Until now our focus was mainly .net framework support, since we want to support all .net projects.
