### ISSUE TITLE
Stryker cannot rollback node AspNetCore

### ISSUE THREAD

**Issue by wmeints** [stryker-mutator/stryker-net#298] opened 2018-12-31 18:05 UTC
I'm trying to get Stryker.NET working on my code, but it can't mutate it properly. It chokes on compiling the code after it succesfully applied the mutations.

![image](https://user-images.githubusercontent.com/1550763/50565351-4774bb80-0d2e-11e9-922e-a3c1e767497b.png)

It seems like it can't find the types. There is a reference to the ASP.NET Core 2.2 package in my project. Additionally I've added the same reference to my test project in the hope that Stryker can find it. But it can't at the moment.

I've attached the log with `trace` level enabled to this issue.

[debug.log](https://github.com/stryker-mutator/stryker-net/files/2718755/debug.log)

**Comment by wmeints** [comment] 2018-12-31 18:16
Turns out that setting the `projectName` setting to an invalid value will cause the behavior. It would be nice if the tool checks that the project reference exists in the project file. This will trip people up :-)

**Comment by richardwerkman** [comment] 2019-01-02 12:08
@wmeints What setting do you mean? The `project-file` setting in the stryker config? Or a setting in your csproj file. I now see it would be usefull to log the passed options to stryker as well.

**Comment by vinnytheviking** [comment] 2019-01-04 10:47
Good morning, 

I'm getting the same issue (Rollback mutation failure) but I'm getting it with Run and IWebHost.

_[10:44:59 ERR] Unable to rollback mutation for node Run with diagnostic message 'IWebHost' does not contain a definition for 'Run' and no accessible extension method 'Run' accepting a first argument of type 'IWebHost' could be found (are you missing a using directive or an assembly reference?)
[10:44:59 ERR] Unable to rollback mutation for node WebHost with diagnostic message The name 'WebHost' does not exist in the current context
[10:44:59 ERR] An error occurred during the mutation test run
System.ArgumentException: Node to track is not a descendant of the root._

I tried changing to .net core 2.2 but that doesn't work. 

I'm not sure where to look at the projectName setting.

Any ideas ?

**Comment by wmeints** [comment] 2019-01-06 09:46
@vinnytheviking The `projectName` can be found in the `stryker-config.json` file in the root of the project. It works without it, but I added it just in case I wanted to control additional settings.

**Comment by Mobrockers** [comment] 2019-01-07 08:02
@vinnytheviking Could you provide the full debug log?

**Comment by vinnytheviking** [comment] 2019-01-07 09:55
> @vinnytheviking The `projectName` can be found in the `stryker-config.json` file in the root of the project. It works without it, but I added it just in case I wanted to control additional settings.

@wmeints I couldn't get the stryker-config file to be picked up by the cli. I tried -cp etc but no luck

**Comment by richardwerkman** [comment] 2019-01-07 10:11
@vinnytheviking Did you place the config file in the root folder of your test project? That's where stryker looks for the json file. Also I'm a bit confused by the log. 

It looks like somehow the compiled project is missing important references to some .dll's. The compile errors in the log don't seem to be caused by any mutations. Could this be because of the .net core 2.2 preview? I don't think it's a coincidence that this issue was found just after the release of 2.2.

**Comment by vinnytheviking** [comment] 2019-01-07 11:03
Hi @richardwerkman

I did put it in the root of the unit test project.

I tried changing the .net core version to an earlier version with no luck.

The project itself builds and runs fine, it's just stryker throwing those exceptions

**Comment by richardwerkman** [comment] 2019-01-07 11:43
@vinnytheviking Could you send me a project to reproduce the issue? This friday I'll have time to look at this.

**Comment by Mobrockers** [comment] 2019-01-20 19:17
Seeing as @wmeints has found the issue and detecting this issue in the future has been improved by #307, I believe this issue can be closed. @wmeints @vinnytheviking Any objections? Anything else you think we should look at regarding this issue?

**Comment by Mobrockers** [comment] 2019-02-03 17:12
I am gonna close this issue. @vinnytheviking If you are still experiencing issues getting stryker to run on your project, feel free to open a new issue so we can take a look.

**Closed by Mobrockers** 2019-02-03 17:12 UTC
