### ISSUE TITLE
Allow mutating transitive project references.

### ISSUE THREAD

**Issue by Kuinox** [stryker-mutator/stryker-net#1726] opened 2021-10-29 00:23 UTC
**Is your feature request related to a problem? Please describe.**
First I recommend this blogposts about testing: https://blog.7mind.io/constructive-test-taxonomy.html
For these reason, I prefer to do E2E/Integrations tests over unit tests when possible and cost efficient, to reduce maintenance cost.

Doing this lead thats some internal libraries are mostly indirectly tested through the test suit.
Intermediary projects are both tested by their own unit tests, and by the tests of their dependents.

Furthermor, segmenting code into multiples assembly is a common thing to do, and a single projects hardly ever hits 100% coverage with it's test suit.

Allowing transitive project reference to be mutated would allow to run the whole test suit on it, and benefit from a far greater coverage than it's own unit test.

**Describe the solution you'd like**
Allow mutating transitive project references.

**Describe alternatives you've considered**
I can write a tool that explicitly add the project dependency before running the command, but I prefer when things run without hacks like this :p.

**Comment by stiasta** [comment] 2022-03-04 09:08
We have this exact problem with .NET projects. We usually split the code into multiple projects and add project references.
Here is a sample project:
```
- Common
- Infrastructure
- WebApi
    References:
    > Infrastructure
        > Common
    > Common
- WebApi.IntegrationTests <---- These test have around 90% code coverage
    References:
    > WebApi
```

**Comment by rouke-broersma** [comment] 2022-11-25 13:23
How would we know where to stop transitively resolving projects under test?

@stiasta the solution runs implementation does not help you, because we make a mapping for test project -> source project based on project references.

I don't think this is something we can support, because it's a giant rabbit hole to fall in. If a test project tests a given source project, add the project reference and the problem is solved. Explicit > Transitive in this case. It doesn't cost you anything either as those references are perfectly legal.

**Closed by rouke-broersma** 2022-11-25 13:23 UTC
Labels: 🚀 Feature request, Area: Compiling

**Comment by Kuinox** [comment] 2022-11-27 21:55
> How would we know where to stop transitively resolving projects under test?

With an user provided list, or pattern for example.

**Comment by rouke-broersma** [comment] 2022-11-28 09:07
I don't think that is something we will support, sorry.
