### ISSUE TITLE
Receiving file not found exception at start of Stryker run.

### ISSUE THREAD

**Issue by wmeints** [stryker-mutator/stryker-net#1195] opened 2020-09-09 06:22 UTC
**Describe the bug**
I'm receiving a file not found exception when running `dotnet stryker` without any configuration.
It looks like it's looking for the original dll file, but in the wrong location.

**Logs**
```
Original project under test D:\code\fmo-group-structure\src\FMO.PDM.GroupStructure\bin\Debug\netcoreapp3.1\FMO.PDM.GroupStructure.dll could not be loaded.
Embedded Resources might be missing.
System.IO.FileNotFoundException: Could not find file 'D:\code\fmo-group-structure\src\FMO.PDM.GroupStructure\bin\Debug\netcoreapp3.1\FMO.PDM.GroupStructure.dll'.
File name: 'D:\code\fmo-group-structure\src\FMO.PDM.GroupStructure\bin\Debug\netcoreapp3.1\FMO.PDM.GroupStructure.dll'
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Mono.Cecil.ModuleDefinition.GetFileStream(String fileName, FileMode mode, FileAccess access, FileShare share)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at Stryker.Core.Initialisation.EmbeddedResourcesGenerator.LoadModule(String assemblyPath, ILogger logger) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Initialisation\EmbeddedResourcesGenerator.cs:line 42
```

**Expected behavior**
No error, because the DLL is there.

**Desktop (please complete the following information):**
 - OS: Windows 10 build 1909
 - Type of project: core
 - Framework Version: 3.1.401
 - Stryker Version: 0.19.0

**Comment by Mobrockers** [comment] 2021-02-05 15:42
Duplicate of #756

**Closed by Mobrockers** 2021-02-05 15:42 UTC
Labels: bug
