### ISSUE TITLE
Failure to build project with modified IntermediateOutputPath

### ISSUE THREAD

**Issue by eatdrinksleepcode** [stryker-mutator/stryker-net#2083] opened 2022-06-13 06:07 UTC
**Describe the bug**
Running Stryker on a project with a modified `IntermediateOutputPath` MSBuild property results in two copies of the `*AssemblyInfo.cs` file being generated and included in the build, which results in build errors ("Duplicate 'System.Reflection.AssemblyVersionAttribute' attribute").

**Logs**
This repro was captured using the repository at https://github.com/eatdrinksleepcode/StrykerBugRepro and executing the commands in the [repro.sh](https://github.com/eatdrinksleepcode/StrykerBugRepro/blob/main/repro.sh) file.
<details>
<summary>Repro</summary>
❯ cat Directory.Build.props

&lt;Project&gt;

  &lt;PropertyGroup&gt;
    &lt;Company&gt;Repro Company&lt;/Company&gt;
    &lt;Product&gt;Repro Product&lt;/Product&gt;
    &lt;Authors&gt;Repro Author&lt;/Authors&gt;
    &lt;Copyright&gt;Copyright (c) Repro Company&lt;/Copyright&gt;
    &lt;OriginalSolutionDir&gt;<span>$</span>(SolutionDir)&lt;/OriginalSolutionDir&gt;
    &lt;SolutionDir Condition=&quot;'<span>$</span>(SolutionDir)'==''&quot;&gt;<span>$</span>(MSBuildThisFileDirectory)&lt;/SolutionDir&gt;
    &lt;BaseIntermediateOutputPath&gt;<span>$</span>(SolutionDir)obj\\<span>$</span>(Configuration)\\<span>$</span>(MSBuildProjectName)\\&lt;/BaseIntermediateOutputPath&gt;
    &lt;IntermediateOutputPath&gt;<span>$</span>(BaseIntermediateOutputPath)&lt;/IntermediateOutputPath&gt;
    &lt;OutputPath&gt;<span>$</span>(SolutionDir)bin\\<span>$</span>(Configuration)\\&lt;/OutputPath&gt;
    &lt;PublishDir&gt;<span>$</span>(SolutionDir)publish\\<span>$</span>(Configuration)\\&lt;/PublishDir&gt;
    &lt;AppendTargetFrameworkToOutputPath&gt;False&lt;/AppendTargetFrameworkToOutputPath&gt;
    &lt;RuntimeFrameworkVersion&gt;3.1.12&lt;/RuntimeFrameworkVersion&gt;
  &lt;/PropertyGroup&gt;
  
  &lt;Target Name=&quot;EchoPath&quot; BeforeTargets=&quot;BeforeCompile&quot;&gt;
    &lt;Message Text=&quot;<span>$</span>(ProjectName).OriginalSolutionDir = <span>$</span>(OriginalSolutionDir)&quot; Importance=&quot;high&quot;/&gt;
    &lt;Message Text=&quot;<span>$</span>(ProjectName).SolutionDir = <span>$</span>(SolutionDir)&quot; Importance=&quot;high&quot;/&gt;
    &lt;Message Text=&quot;<span>$</span>(ProjectName).BaseIntermediateOutputPath = <span>$</span>(BaseIntermediateOutputPath)&quot; Importance=&quot;high&quot;/&gt;
    &lt;Message Text=&quot;<span>$</span>(ProjectName).IntermediateOutputPath = <span>$</span>(IntermediateOutputPath)&quot; Importance=&quot;high&quot;/&gt;
  &lt;/Target&gt;
&lt;/Project&gt;

❯ dotnet clean -v minimal &amp;&amp; rm -r **/bin **/obj

Microsoft (R) Build Engine version 16.7.2+b60ddb6f4 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

❯ find . -name &quot;*AssemblyInfo.cs&quot; # There are no AssemblyInfo.cs files before building

❯ dotnet build

Microsoft (R) Build Engine version 16.7.2+b60ddb6f4 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored /Users/dnelson/Projects/StrykerBugRepro/MainProj/MainProj.csproj (in 195 ms).
  Restored /Users/dnelson/Projects/StrykerBugRepro/TestProj/TestProj.csproj (in 1.85 sec).
  MainProj.OriginalSolutionDir = /Users/dnelson/Projects/StrykerBugRepro/
  MainProj.SolutionDir = /Users/dnelson/Projects/StrykerBugRepro/
  MainProj.BaseIntermediateOutputPath = /Users/dnelson/Projects/StrykerBugRepro/obj/Debug/MainProj/
  MainProj.IntermediateOutputPath = /Users/dnelson/Projects/StrykerBugRepro/obj/Debug/MainProj/
  MainProj -&gt; /Users/dnelson/Projects/StrykerBugRepro/bin/Debug/MainProj.dll
  TestProj.OriginalSolutionDir = /Users/dnelson/Projects/StrykerBugRepro/
  TestProj.SolutionDir = /Users/dnelson/Projects/StrykerBugRepro/
  TestProj.BaseIntermediateOutputPath = /Users/dnelson/Projects/StrykerBugRepro/obj/Debug/TestProj/
  TestProj.IntermediateOutputPath = /Users/dnelson/Projects/StrykerBugRepro/obj/Debug/TestProj/
  TestProj -&gt; /Users/dnelson/Projects/StrykerBugRepro/bin/Debug/TestProj.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:05.36

❯ find . -name &quot;*AssemblyInfo.cs&quot; # Each project has a generated AssemblyInfo.cs file at the configured IntermediateOutputPath

./obj/Debug/MainProj/MainProj.AssemblyInfo.cs
./obj/Debug/TestProj/TestProj.AssemblyInfo.cs

❯ dotnet clean -v minimal &amp;&amp; rm -r **/bin **/obj

Microsoft (R) Build Engine version 16.7.2+b60ddb6f4 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

❯ dotnet stryker --log-to-file -tp TestProj -p MainProj

   _____ _              _               _   _ ______ _______  
  / ____| |            | |             | \ | |  ____|__   __| 
 | (___ | |_ _ __ _   _| | _____ _ __  |  \| | |__     | |    
  \___ \| __| '__| | | | |/ / _ \ '__| | . ` |  __|    | |    
  ____) | |_| |  | |_| |   &lt;  __/ |    | |\  | |____   | |    
 |_____/ \__|_|   \__, |_|\_\___|_| (_)|_| \_|______|  |_|    
                   __/ |                                      
                  |___/                                       

Version: 2.0.0

[00:51:10 INF] Identifying project to mutate.
[00:51:12 INF] The project /Users/dnelson/Projects/StrykerBugRepro/MainProj/MainProj.csproj will be mutated.
[00:51:14 WRN] Buildalyzer could not find sourcefiles. This should not happen. Will fallback to filesystem scan. Please report an issue at github.
[00:51:14 INF] Analysis complete.
[00:51:14 INF] Building test project /Users/dnelson/Projects/StrykerBugRepro/TestProj/TestProj.csproj (1/1)
[00:51:16 INF] Time Elapsed 00:00:06.5408775
Stryker.NET failed to mutate your project. For more information see the logs below:

Microsoft (R) Build Engine version 16.7.2+b60ddb6f4 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  MainProj.OriginalSolutionDir = 
  MainProj.SolutionDir = /Users/dnelson/Projects/StrykerBugRepro/
  MainProj.BaseIntermediateOutputPath = /Users/dnelson/Projects/StrykerBugRepro/obj/MainProj/
  MainProj.IntermediateOutputPath = /Users/dnelson/Projects/StrykerBugRepro/obj/MainProj/
/Users/dnelson/Projects/StrykerBugRepro/obj/MainProj/MainProj.AssemblyInfo.cs(13,12): error CS0579: Duplicate 'System.Reflection.AssemblyCompanyAttribute' 
attribute [/Users/dnelson/Projects/StrykerBugRepro/MainProj/MainProj.csproj]
/Users/dnelson/Projects/StrykerBugRepro/obj/MainProj/MainProj.AssemblyInfo.cs(14,12): error CS0579: Duplicate 
'System.Reflection.AssemblyConfigurationAttribute' attribute [/Users/dnelson/Projects/StrykerBugRepro/MainProj/MainProj.csproj]
/Users/dnelson/Projects/StrykerBugRepro/obj/MainProj/MainProj.AssemblyInfo.cs(15,12): error CS0579: Duplicate 'System.Reflection.AssemblyCopyrightAttribute' 
attribute [/Users/dnelson/Projects/StrykerBugRepro/MainProj/MainProj.csproj]
/Users/dnelson/Projects/StrykerBugRepro/obj/MainProj/MainProj.AssemblyInfo.cs(16,12): error CS0579: Duplicate 
'System.Reflection.AssemblyFileVersionAttribute' attribute [/Users/dnelson/Projects/StrykerBugRepro/MainProj/MainProj.csproj]
/Users/dnelson/Projects/StrykerBugRepro/obj/MainProj/MainProj.AssemblyInfo.cs(17,12): error CS0579: Duplicate 
'System.Reflection.AssemblyInformationalVersionAttribute' attribute [/Users/dnelson/Projects/StrykerBugRepro/MainProj/MainProj.csproj]
/Users/dnelson/Projects/StrykerBugRepro/obj/MainProj/MainProj.AssemblyInfo.cs(18,12): error CS0579: Duplicate 'System.Reflection.AssemblyProductAttribute' 
attribute [/Users/dnelson/Projects/StrykerBugRepro/MainProj/MainProj.csproj]
/Users/dnelson/Projects/StrykerBugRepro/obj/MainProj/MainProj.AssemblyInfo.cs(19,12): error CS0579: Duplicate 'System.Reflection.AssemblyTitleAttribute' 
attribute [/Users/dnelson/Projects/StrykerBugRepro/MainProj/MainProj.csproj]
/Users/dnelson/Projects/StrykerBugRepro/obj/MainProj/MainProj.AssemblyInfo.cs(20,12): error CS0579: Duplicate 'System.Reflection.AssemblyVersionAttribute' 
attribute [/Users/dnelson/Projects/StrykerBugRepro/MainProj/MainProj.csproj]

Build FAILED.

/Users/dnelson/Projects/StrykerBugRepro/obj/MainProj/MainProj.AssemblyInfo.cs(13,12): error CS0579: Duplicate 'System.Reflection.AssemblyCompanyAttribute' 
attribute [/Users/dnelson/Projects/StrykerBugRepro/MainProj/MainProj.csproj]
/Users/dnelson/Projects/StrykerBugRepro/obj/MainProj/MainProj.AssemblyInfo.cs(14,12): error CS0579: Duplicate 
'System.Reflection.AssemblyConfigurationAttribute' attribute [/Users/dnelson/Projects/StrykerBugRepro/MainProj/MainProj.csproj]
/Users/dnelson/Projects/StrykerBugRepro/obj/MainProj/MainProj.AssemblyInfo.cs(15,12): error CS0579: Duplicate 'System.Reflection.AssemblyCopyrightAttribute' 
attribute [/Users/dnelson/Projects/StrykerBugRepro/MainProj/MainProj.csproj]
/Users/dnelson/Projects/StrykerBugRepro/obj/MainProj/MainProj.AssemblyInfo.cs(16,12): error CS0579: Duplicate 
'System.Reflection.AssemblyFileVersionAttribute' attribute [/Users/dnelson/Projects/StrykerBugRepro/MainProj/MainProj.csproj]
/Users/dnelson/Projects/StrykerBugRepro/obj/MainProj/MainProj.AssemblyInfo.cs(17,12): error CS0579: Duplicate 
'System.Reflection.AssemblyInformationalVersionAttribute' attribute [/Users/dnelson/Projects/StrykerBugRepro/MainProj/MainProj.csproj]
/Users/dnelson/Projects/StrykerBugRepro/obj/MainProj/MainProj.AssemblyInfo.cs(18,12): error CS0579: Duplicate 'System.Reflection.AssemblyProductAttribute' 
attribute [/Users/dnelson/Projects/StrykerBugRepro/MainProj/MainProj.csproj]
/Users/dnelson/Projects/StrykerBugRepro/obj/MainProj/MainProj.AssemblyInfo.cs(19,12): error CS0579: Duplicate 'System.Reflection.AssemblyTitleAttribute' 
attribute [/Users/dnelson/Projects/StrykerBugRepro/MainProj/MainProj.csproj]
/Users/dnelson/Projects/StrykerBugRepro/obj/MainProj/MainProj.AssemblyInfo.cs(20,12): error CS0579: Duplicate 'System.Reflection.AssemblyVersionAttribute' 
attribute [/Users/dnelson/Projects/StrykerBugRepro/MainProj/MainProj.csproj]
    0 Warning(s)
    8 Error(s)

Time Elapsed 00:00:01.62

Initial build of targeted project failed. Please make sure the targeted project is buildable. You can reproduce this error yourself using: &quot;dotnet build &quot;TestProj.csproj&quot;&quot;

❯ find . -name &quot;*AssemblyInfo.cs&quot; # In addition to the AssemblyInfo.cs files at the configured IntermediateOutputPath, there is a duplicate AssemblyInfo.cs file at the same relative path under the project directory

./obj/MainProj/MainProj.AssemblyInfo.cs
./MainProj/obj/MainProj/MainProj.AssemblyInfo.cs
./TestProj/obj/TestProj/TestProj.AssemblyInfo.cs

</details>

[log-20220613.txt](https://github.com/stryker-mutator/stryker-net/files/8888310/log-20220613.txt)

**Expected behavior**
Stryker should build the project successfully, just as `dotnet build` does, without generating duplicate `AssemblyInfo.cs` files.

**Desktop (please complete the following information):**
 - OS: macOS 11.6.6
 - .NET Core 3.1
 - Stryker Version 2.0.0 (as a global tool)

**Additional context**
Note that the [Directory.Build.props](https://github.com/eatdrinksleepcode/StrykerBugRepro/blob/main/Directory.Build.props) file has a custom target which prints key paths. One difference that I noticed between the successful `dotnet build` and the unsuccessful `dotnet stryker` is that Stryker is not setting the `SolutionDir` property, while the normal build is. I thought that might be important since the modified `IntermediateOutputPath` is dependent on `SolutionDir`. However, the `Directory.Build.props` file correctly sets the `SolutionDir` if it is not provided; and that also would not explain why there end up being duplicate `AssemblyInfo.cs` files, instead of just one in the wrong place.

There is an [open Buildalyzer issue](https://github.com/daveaglick/Buildalyzer/issues/205) which seems somewhat similar, but there is no additional information.

**Comment by rouke-broersma** [comment] 2022-08-05 07:16
Apologies for not replying to you yet. These issues are pretty common in a number of scenarios. See for example #2077. So far I have not found a way to deal with this. We are not receiving this information from buildalyzer, which suggests that msbuild is doing some internal magic or using some msbuild targets that buildalyzer is not. This is extermely difficult to investigate and track. Thank you for the reproduction project, when we get around to investigating this that will be a great help.

**Comment by rouke-broersma** [comment] 2023-05-05 15:37
Close as duplicate of #2077

**Closed by rouke-broersma** 2023-05-05 15:37 UTC
Labels: 🐛 Bug, Area: Buildalyzer
