### ISSUE TITLE
Wrong SourceFile

### ISSUE THREAD

**Issue by AngryRectangle** [stryker-mutator/stryker-net#1931] opened 2022-02-25 21:04 UTC
**Describe the bug**
Strykers fails to find AssemblyInfo.cs file while running because it is searching for wrong file.

**Expected behavior**
Source file should be A:\Project\Azure\ServerlessSteamAnalytic\ServerlessSteamAnalytic\obj\Release\net6.0\ServerlessSteamAnalytic.AssemblyInfo.cs
not
A:\Project\Azure\ServerlessSteamAnalytic\ServerlessSteamAnalytic\obj\Release\net6.0\WorkerExtensions.AssemblyInfo.cs
**Logs**
[log-20220226.txt](https://github.com/stryker-mutator/stryker-net/files/8144828/log-20220226.txt)
**Desktop (please complete the following information):**
 - OS: Windows 10 x64

 - Just regular project with Azure functions
 - .net 6.0
 - Stryker Version 1.3.1

**Additional context**

**Comment by rouke-broersma** [comment] 2022-03-02 13:25
Thank you for reporting this. It seems that we do not properly support azure functions.

Closing as duplicate of #1859

**Closed by rouke-broersma** 2022-03-02 13:25 UTC
Labels: 🐛 Bug
