### ISSUE TITLE
Potential problem with coverage analysis on async tests

### ISSUE THREAD

**Issue by joao2391** [stryker-mutator/stryker-net#1144] opened 2020-07-19 08:01 UTC
```C#
//First Scenario
[HttpPut("api/myendpoint01")]
public async Task<IActionResult> MyEndPoint01(string param)
{
 //Here the mutant is killed
 if(string.IsNullOrEmpty(param))
 {
   //Do something...
   return BadRequest();
 }
 //.......
}
//Second Scenario
[HttpPut("api/myendpoint02")]
public async Task<IActionResult> MyEndPoint02(string param)
{
 //Here the mutant is survived
 if(string.IsNullOrEmpty(param))
 {
   //Do something...
   return BadRequest();
 }

 //....... 
 
}
```

I've got the unit test for both endpoint covering the BadRequest result and Ok result.

My question is why in the first scenario the mutant is killed but in the second one it is survived?

### Info:
Windows 10 Pro
.NET Core 2.1.509
NUnit 3.12.0
Stryker 0.18.0

**Comment by Mobrockers** [comment] 2020-07-19 13:40
Hi! We would also need to see this unit tests to see why one is killed and the other is not.

**Comment by joao2391** [comment] 2020-07-20 18:06
```C#
 var jsonToTest = @"{'foo':'foovalue'}";
//......
[Test]
public async Task BadRequest_Test_Method_Async()
{
 var obj = JsonConvert.DeserializeObject<MyClass>(jsonToTest);

 var result = await myController.MyEndpoint02(obj.Foo);

 var badReq = new  BadReqiestObjectResult(result);

 var statusCode = badReq.StatusCode;

 Assert.AreEqual(400, statusCode);
}
```

The endpoint that the mutant is killed has the same test that this one.

**Comment by Mobrockers** [comment] 2020-07-22 08:15
Would you be able to share the part of the report showing both mutations with one as killed and one as not-killed?

**Comment by joao2391** [comment] 2020-07-22 18:06
@Mobrockers 
Killed:
![Killed](https://user-images.githubusercontent.com/17519344/88211786-934ac680-cc2c-11ea-9291-78300f031142.png)
Survived:
![Survived](https://user-images.githubusercontent.com/17519344/88211820-9f368880-cc2c-11ea-9248-10a32c854dea.png)

**Comment by dupdob** [comment] 2020-07-22 21:02
Hi!
Here is a procedure to help us identify where the problem is:
Whenever you have an unexpected surviving mutant, you should:

1. **Manually inject the mutant in your code and run your tests**. In your case, I think it means replacing `if (string.IsNullOrEmpty(...))` by `if (!string.IsNullOrEmpty(...))`

1. **If the test run succeeds**, it is indeed a surviving mutant and **you need to add a new test** or change an existing test that fails due to this mutation.

1. **if the test run fails, it means StrykerMutator failed** to see it as killed* Stryker should probably have run more tests against this mutation. Which means coverage analysis results where wrong. Please try again with coverage analysis turned off (see the [Configuration.md](https://github.com/stryker-mutator/stryker-net/blob/master/docs/Configuration.md#coverage-analysis) file). This is going to be slow.
   1. If the problem is fixed (i.e the mutant is killed), please perform another run with coverage analysis on and with debug log and provide the main log file (largest one) with the issue. It may be sufficient to fix the issue.
  1. if the problem is not fixed, please open an issue, but we will probably need access to the project or to a project that can reproduce the issue.

**Comment by joao2391** [comment] 2020-07-23 13:54
I'll try it and report to you asap.
Thank you very much!

**Comment by rodrigogurgel** [comment] 2020-07-23 22:33
Try it dotnet stryker -tr dotnettest

**Comment by joao2391** [comment] 2020-07-24 08:08
Thank you @rodrigogurgel ! It works!
Thank you guys for your help!

**Comment by Mobrockers** [comment] 2020-07-24 08:44
Be advised, the dotnet testrunner is potentially much slower than the vstest runner. Your problem shows there's a potential issue in coverage analysis that we need to fix, so I think it's best if we keep this issue open.

**Comment by dupdob** [comment] 2020-07-24 08:48
Thanks @Mobrockers : I was about to say the same thing here. It sounds like a coverage issue. I lack experience with tests marked as 'async' but those could potentially result in invalid coverage data.

**Comment by joao2391** [comment] 2020-07-24 11:22
Unfortunately I can't share the original code but asap I'll share with you a repo to reproduce this scenario.

**Comment by joao2391** [comment] 2020-07-24 11:24
> 
> 
> Hi!
> Here is a procedure to help us identify where the problem is:
> Whenever you have an unexpected surviving mutant, you should:
> 
>     1. **Manually inject the mutant in your code and run your tests**. In your case, I think it means replacing `if (string.IsNullOrEmpty(...))` by `if (!string.IsNullOrEmpty(...))`
> 
>     2. **If the test run succeeds**, it is indeed a surviving mutant and **you need to add a new test** or change an existing test that fails due to this mutation.
> 
>     3. **if the test run fails, it means StrykerMutator failed** to see it as killed* Stryker should probably have run more tests against this mutation. Which means coverage analysis results where wrong. Please try again with coverage analysis turned off (see the [Configuration.md](https://github.com/stryker-mutator/stryker-net/blob/master/docs/Configuration.md#coverage-analysis) file). This is going to be slow.
>        
>        1. If the problem is fixed (i.e the mutant is killed), please perform another run with coverage analysis on and with debug log and provide the main log file (largest one) with the issue. It may be sufficient to fix the issue.
>        2. if the problem is not fixed, please open an issue, but we will probably need access to the project or to a project that can reproduce the issue.
> 
> 
> Can you please try this and report you results please?

I've tried these steps but the report was the same.

**Comment by dupdob** [comment] 2020-07-24 12:58
thanks. Please confirm I understood you correctly:
1 - manual testing resulted in having the mutant properly killed by your tests (i.e your tests fail)
2 - running stryker with coverage analysis turned off still resulted in stryker marking this mutant as a survivor

correct?

**Comment by joao2391** [comment] 2020-08-01 15:51
I had to install VS 2017 Enterprise and after installed it all worked fine. I don't know if it has something to do with the issue.
I've created [this repo](https://github.com/joao2391/Stryker) to reproduce the scenario( in my personal laptop. I have VS 2017 Community and VS2019 Community) and all worked fine too. 
If you want to close this issue I think it's OK.

**Comment by Mobrockers** [comment] 2020-08-01 16:24
> I had to install VS 2017 Enterprise and after installed it all worked fine. I don't know if it has something to do with the issue.
> I've created [this repo](https://github.com/joao2391/Stryker) to reproduce the scenario( in my personal laptop. I have VS 2017 Community and VS2019 Community) and all worked fine too. 
> If you want to close this issue I think it's OK.

Wait, you're saying the issue is no longer there now that you installed vs2017?

**Comment by joao2391** [comment] 2020-08-10 11:25
@Mobrockers Yes.

**Comment by dupdob** [comment] 2021-11-02 07:42
Should we close this issue?

**Comment by rouke-broersma** [comment] 2021-11-02 10:47
I am slightly worried by the fix being installing vs2017 but let's close this for now.

**Closed by rouke-broersma** 2021-11-02 10:47 UTC
Labels: 🐛 Bug, Repro needed, Feat: Coverage Analysis
