### ISSUE TITLE
Stryker.NET doesn't finish when multiple testing projects used

### ISSUE THREAD

**Issue by ohoward2001** [stryker-mutator/stryker-net#1867] opened 2022-01-19 17:15 UTC
Stryker will get stuck at a certain point and just stay frozen indefinitely. This only appears to be a problem when multiple testing projects are used. This happens randomly and does not occur everytime. The below screenshot is an hour and 20 minutes after running when it usually takes 10 minutes. 
![image](https://user-images.githubusercontent.com/86209005/150181095-728cd0c5-595b-4718-bb4c-02666901bdfc.png)

**Comment by richardwerkman** [comment] 2022-01-20 12:15
This is a known issue in vstest that should be fixed soon. You can follow the progress here https://github.com/microsoft/vstest/pull/3186

**Comment by richardwerkman** [comment] 2022-01-21 09:48
duplicate of #1136

**Closed by richardwerkman** 2022-01-21 09:48 UTC
