### ISSUE TITLE
Provide a report with coverage report and detailed test results

### ISSUE THREAD

**Issue by dupdob** [stryker-mutator/stryker-net#648] opened 2019-08-02 09:57 UTC
**Is your feature request related to a problem? Please describe.**
A fine grain view of coverage and test results can provide useful guidance to a project team. E.G:
- providing the list of tests that can be improved to kill a surviving mutants
- providing the list of 'useless' tests, i.e tests that kill no mutant whatsoever
- providing a list of 'duplicate' tests, i.e. tests that test and kills the same mutants
....

**Describe the solution you'd like**
Store detailed result of the test run and publish them through a new reporter

**Describe alternatives you've considered**
None available

**Additional context**
I have a working implementation in a branch

**Comment by richardwerkman** [comment] 2019-08-08 14:25
Does your working implementation report to the console? If we want this information available in the html report we should work together with the mutation testing elements team to add room for this information.

**Comment by dupdob** [comment] 2019-08-10 14:08
As of now, it just generates a json file. I am working on a separate command line app that parses and analyses this file in order to explore what kind of information can be extracted.
That's how I confirmed there was potential value in testing multiple mutants simultaneously.

Ultimately, I think the interesting analysis will be part of the html report. We just need to figure out which ones are really interesting...

**Comment by rouke-broersma** [comment] 2022-08-05 07:56
Duplicate of #1565

**Closed by rouke-broersma** 2022-08-05 07:56 UTC
Labels: 🚀 Feature request, Area: Reporters
