### ISSUE TITLE
Crash when code combines tuple deconstruction with ternary operator

### ISSUE THREAD

**Issue by theunrepentantgeek** [stryker-mutator/stryker-net#125] opened 2018-10-01 19:09 UTC
On a small personal project to implement an immutable priority queue, Stryker.NET crashes with the following error:
```
[07:59:19 ERR] Unable to rollback mutation for node head with diagnosticmessage The name 'head' does not exist in the current context
[07:59:19 ERR] An error occurred during the mutationtest run
System.ArgumentException: Node to track is not a descendant of the root.
   at Microsoft.CodeAnalysis.SyntaxNodeExtensions.TrackNodes[TRoot](TRoot root, IEnumerable`1 nodes) in /_/src/Compilers/Core/Portable/Syntax/SyntaxNodeExtensions_Tracking.cs:line 43
   at Stryker.Core.Compiling.RollbackProcess.RemoveMutantIfStatements(SyntaxTree originalTree, ICollection`1 diagnosticInfo)
   at Stryker.Core.Compiling.RollbackProcess.Start(CSharpCompilation compiler, ImmutableArray`1 diagnostics)
   at Stryker.Core.Compiling.CompilingProcess.Compile(IEnumerable`1 syntaxTrees, MemoryStream ms)
   at Stryker.Core.MutationTest.MutationTestProcess.Mutate()
   at Stryker.Core.StrykerRunner.RunMutationTest(StrykerOptions options)
[07:59:19 INF] Time Elapsed 00:00:10.8997693
```

Using the `--logConsole trace` flag I was able to isolate the cause to this piece of code:
```
var (head, toEnqueue) = _comparer(Head, value) <= 0
    ? (Head, value)
    : (value, Head);
``` 
BTW: thank you for including good diagnostic support!

As a workaround, I modified the code by removing use of tuples and the ternary operator:
```
T head;
T toEnqueue;
if (_comparer(Head, value) <= 0)
{
    head = Head;
    toEnqueue = value;
}
else
{
    head = value;
    toEnqueue = Head;
}
```

With this change, Stryker.NET doesn't crash on this piece of code ... though it does crash on two other very similar examples. Once those were similarly amended, all the mutants were tested - and bugs were identified. 😄 

A simple ternary operator seems to be fine, and tuple deconstruction that doesn't require mutation also seems to be fine, so I suspect the problem occurs only with both language features combined.

**Comment by simondel** [comment] 2018-10-01 19:20
Thanks for the detailed issue! We'll need to fix this :) We don't want to go around losing your head ;)

**Comment by richardwerkman** [comment] 2018-10-02 19:36
After some research I was able to reproduce the issue. I think this is an duplicate of #17. 

LocalDeclarationStatements are ignored from mutating right now because this causes compile errors. You seem to have found a different kind of statement that causes this:

``` csharp
var (head, toEnqueue) = 1 > 0 ? ("test", "test2") : ("test2", "test");

var test = head;
```
Gets mutated into:
``` csharp
if(Environment.GetEnvironmentVariable("ActiveMutation") == "1") {
    var (head, toEnqueue) = 1 < 0 ? ("test", "test2") : ("test2", "test");
} else {
    var (head, toEnqueue) = 1 > 0 ? ("test", "test2") : ("test2", "test");
}
var test = head;
```
The if statements causes a change in the scope of the declaration of `string head`

**Comment by Mobrockers** [comment] 2018-10-23 09:56
Close as duplicate of #17

**Closed by Mobrockers** 2018-10-23 09:56 UTC
Labels: duplicate
