### ISSUE TITLE
Stryker.NET encountered an compile error

### ISSUE THREAD

**Issue by mapspiral** [stryker-mutator/stryker-net#971] opened 2020-03-09 07:54 UTC
**Describe the bug:**
We run Stryker.NET against our code base and the runner executes successfully, but with this warning in the log and a message indicating that it should be reported on Github.

**Logs:**
[Stryker.log](https://github.com/stryker-mutator/stryker-net/files/4305271/Stryker.log)

**Expected behavior:**
The Stryker runner should execute without warnings.

**Desktop:**
 - OS: Windows Server 2019
 - Type of project: Framework
 - Framework Version 4.7.1
 - Stryker Version 0.16.1 (beta)

**Additional context**
There are 4 similar issues that all show another exception, so including this one just in case.

**Comment by Mobrockers** [comment] 2020-03-09 08:06
This looks like a duplicate of #642 

This has been fixed on master but has not been released yet. Thank you for reporting on the error!

We will probably release a new version within the next two weeks to address this issue.

**Closed** 2020-03-20 17:07 UTC
Labels: bug, fixed in master
