### ISSUE TITLE
An error occurred during the mutation test run : Internal error due to compile error

### ISSUE THREAD

**Issue by ggingras** [stryker-mutator/stryker-net#844] opened 2019-12-09 16:28 UTC
An error occurred during the mutation test run: Internal error due to compile error

**Logs**
[vstest-log.txt](https://github.com/stryker-mutator/stryker-net/files/3940678/vstest-log.txt)
[log-20191209.txt](https://github.com/stryker-mutator/stryker-net/files/3940679/log-20191209.txt)

**Environment:**
 - Windows 10
 - .Net 4.7.1 (WPF app)
 - Stryker-net 0.14.3

**Additional context**
According to log, it seems related to SearchMode enum, so here real implementation :

```
public enum SearchMode
    {
        TwoDays = 2,
        SevenDays = 7,
        ThirtyDays = 30,
        SixtyDays = 60,
        SpecificDate = -1
    }
```

**Comment by Mobrockers** [comment] 2019-12-10 09:32
Thank you for the report.

The problem is this mutation we generated:

```csharp
public AppEnums.ResourceCategory SelectedResourceCategory
		{
			get
			{
				if ((StrykerJzg5CEjSQGUF4UA.MutantControl.IsActive(21930)?!(ResourceCategory?.SelectedValue?.Value != null):(StrykerJzg5CEjSQGUF4UA.MutantControl.IsActive(21929)?ResourceCategory?.SelectedValue?.Value == null:ResourceCategory?.SelectedValue?.Value != null)))
					return (StrykerJzg5CEjSQGUF4UA.MutantControl.IsActive(21931)?!(Enum.TryParse(ResourceCategory.SelectedValue.Value.ToString(), out AppEnums.ResourceCategory category) ):Enum.TryParse(ResourceCategory.SelectedValue.Value.ToString(), out AppEnums.ResourceCategory category) )? category : AppEnums.ResourceCategory.Vehicle;

				return AppEnums.ResourceCategory.Vehicle;
			}
		}
```

It is invalid due to the out variable I think, it causes the variable to be declared twice which is not valid.

**Comment by ggingras** [comment] 2019-12-10 14:44
Thanks for the investigation and follow-up. I guess a modification in Striker will be necessary in order to fix this, right?

In the meantime, I will ignore this file and try to continue with other classes in the project.

Regards,

Gaetan

**Comment by Mobrockers** [comment] 2019-12-10 21:14
Yes, this needs to be fixed in stryker. Unfortunately I don't think ignoring the file will work as we still place the mutations on ignored files, we simply mark them as ignored. This is so that we can show the user in reports that they ignored the mutations.

**Comment by dupdob** [comment] 2019-12-11 14:34
I think the best workaround is to declare category outside of the call, as in:
```
get
  {
     AppEnums.ResourceCategory category;
     ...
```
Note that there is a chance you face a similar issue with other accessors.

This issue highlights two underlying issues:
1. Stryker should not mutate a conditional expression with an inlined variable declarations. Detection logic already exists but clearly need to be extended somehow.
1. Safe mode has been designed to recover from such unexpected failure, but it also failed here. Recover mode needs to be updated to cater for accessors. As of today, it only works for regular methods.

**Comment by Mobrockers** [comment] 2019-12-11 15:04
We are also thinking about changing the ignore behaviour to actually not place the mutations at all, because users don't expect that the mutation is still there (but never activated) and keep running into issues with that.

**Comment by ggingras** [comment] 2019-12-11 15:18
Unfortunately, the workaround will not work for me, since we always use an inlined variable declarations everywhere in the code. I could fix it for this call, but I will have same error on the next inline declaration.

I will try to debug stryker and see if I can fix the problem.

Regards

Gaetan

**Closed** 2019-12-13 08:31 UTC
Labels: bug
