### ISSUE TITLE
Stryker fails to connect to vstest on M1 mac

### ISSUE THREAD

**Issue by dmitryvorobey** [stryker-mutator/stryker-net#2117] opened 2022-07-27 13:44 UTC
**Describe the bug**
Hi guys! I've tried to install the Stryker and run it from the test's directory but it was unsuccessful.
Error message is _"Stryker failed to connect to vstest.console"_
Is it a bug or I doing smth wrong?

**Logs**
Probably it the most useful part of logs 

[16:35:39 DBG] Initial build successful
[16:35:39 DBG] VsTest zip was copied to: /var/folders/0d/kw0r8pcx1rn06j4d2g_bmjj00000gn/T/o2gew0gf.rrm/.vstest/vstest.zip
[16:35:39 DBG] VsTest zip was unzipped to: /var/folders/0d/kw0r8pcx1rn06j4d2g_bmjj00000gn/T/o2gew0gf.rrm/.vstest
[16:35:39 DBG] Using vstest from deployed vstest package
[16:35:39 DBG] Using vstest.console: OSX for OS /var/folders/0d/kw0r8pcx1rn06j4d2g_bmjj00000gn/T/o2gew0gf.rrm/.vstest/tools/netcoreapp2.1/vstest.console.dll
[16:35:39 INF] Time Elapsed 00:00:03.4676349
Unhandled exception. 

Stryker failed to connect to vstest.console

[log-20220727.txt](https://github.com/stryker-mutator/stryker-net/files/9199336/log-20220727.txt)

**Expected behavior**
Stryker should successful mutate code and run tests

**Desktop (please complete the following information):**
 - OS: [MacOS 12.4 (21F79]
 - Type of project [framework, core, xamarin]
 - Framework Version [.NET 6]
 - Stryker Version [version '2.1.0']

**Additional context**
Macbook M1

**Comment by rouke-broersma** [comment] 2022-07-27 14:19
Could you see if you have any vstest logs in the log directory?

**Comment by dmitryvorobey** [comment] 2022-07-27 14:55
I have only 1 log file under the test_folder/Stryker Output/date/logs and you can find it in the description section.
Let me know if I should provide more info.

**Comment by rouke-broersma** [comment] 2022-07-27 16:02
Did you run stryker with `--log-to-file`?

**Comment by dmitryvorobey** [comment] 2022-07-27 20:31
Yeap, it's not a big deal to run it one more time.
There is a new log file in attach
[log-20220727.txt](https://github.com/stryker-mutator/stryker-net/files/9203356/log-20220727.txt)

**Comment by dmitryvorobey** [comment] 2022-07-27 20:32
Upd:
It's a screenshot log folder's content
<img width="715" alt="image" src="https://user-images.githubusercontent.com/106617526/181366583-84be2086-b234-4c13-a2d3-096835545ed3.png">

**Comment by rouke-broersma** [comment] 2022-07-27 21:06
The library we use to connect to vstest.console should have it's own logfile, I expected that log file to be there containing with some hint as to why connection to vstest.console failed. Seems that it has not managed to even do that. 

Unfortunately I do not have a Mac. I think @dupdob has a mac but he has not reported such issues so I doubt they have them. I think it could be that theirs is not an M1 mac. I have a feeling this might be related to M1 macs. In that case we cannot troubleshoot this for you unfortunately.

I think at this point the best course of action is to report this issue over on https://github.com/microsoft/vstest. I could report the issue for you so it has some details on how we integrate with vstest but they will likely ask us to provide some diagnostics or do some tests for us which we cannot do since we cannot currently reproduce this.

Do you think this is something you could assist with after we report the issue with them?

**Comment by dmitryvorobey** [comment] 2022-07-28 06:55
Thanks a lot!
Let me know how I can assist and what kind of info I should provide.
Hope this issue will be resolved in the future.

**Comment by dupdob** [comment] 2022-07-29 08:57
hi
for info, I use Parallel Desktop for OSS C# dev. Alternatively, I use Rider on Mac for some hobby projects. So I do not use Stryker on Mac OS.
If I have some free time, I will give it a spin to see if everything works as expected.

**Comment by dupdob** [comment] 2022-08-04 07:55
I just made a check, ran smoothly on my intel Mac (MBP2020).
So this may be related to M1 Macs

**Comment by dupdob** [comment] 2022-08-04 08:37
for info: I added some logs (in my current PR) as an attempt to get some details on why VsTest fails to start.
This will not fix anything, just give us some more info whenever this happens.

**Comment by libravado** [comment] 2022-08-04 14:38
I am also getting VsTest console timeout errors, as described. I'm on a HP Z-Book running Windows 10. 
Stryker <= 1.5.3 seems ok
Stryker >= 2 all give me the issue

**Comment by dupdob** [comment] 2022-08-04 15:12
hi @libravado 
you short description hints toward a different problem. It looks like #2069 or #2002. Refactoring lead to a redesign of the timeout calculation, with some regressions as a sad by product.
Can you share the project you are testing ?
Alternatively, can you open a specific issue with some details (incl. verbose log files)?

**Comment by rouke-broersma** [comment] 2022-08-05 11:51
@dmitryvorobey I am rolling a new version (2.1.2) where we should get a little more information from the exception that is thrown that could perhaps help us move forward. It should be released within the next hour. If you have time I would appreciate it if you could give it a try and report back with the actual exception.

**Comment by rouke-broersma** [comment] 2022-08-19 14:08
@dmitryvorobey any chance you could help us out here?

**Comment by ysbakker** [comment] 2022-10-30 17:13
I was unable to reproduce this issue on my M1 macbook pro (2020, 16GB) running macOS 12.4. I ran Stryker succesfully on a few projects, and did not encounter any issues.

Let me know if I can test projects more specific to this issue.

**Comment by rouke-broersma** [comment] 2022-10-30 17:49
In that case and since we have had no further reports I will close the issue as not reproducible. Thank you!

**Closed by rouke-broersma** 2022-10-30 17:49 UTC
Labels: 🐛 Bug, Priority: High, ! Need more info !
