### ISSUE TITLE
Stryker freezes with too many concurrent test runners

### ISSUE THREAD

**Issue by psfinaki** [stryker-mutator/stryker-net#1665] opened 2021-08-18 13:11 UTC
**Describe the bug**

We are now executing Stryker during the night against a big codebase. Recently we switched to very strong machines and Stryker suddenly started to "freeze" during executions. After a few days of frustration I figured out that concurrency is the issue. The machines we use now have 16 logical processors so Stryker spins up 8 concurrent test runners and that occasionally (actually more often than not) just leeds to freezes in random places.

I don't know where the problem exactly is. I can figure out the exact number of test runners when things start going bad. Now I only know the 5 are ok and 8 are not ok. For us the execution time is the same for 4 and 5 concurrent test runners so we stopped there.

**Expected behavior**

No freezes, well.

**Workarounds**

Thanks god Stryker has an option to specify this amount in the config. This saved my ass :D

**Comment by rouke-broersma** [comment] 2021-08-18 13:23
We have actually experienced this ourselves before but only when using the solution run or multiple test projects feature! We had never had a user report before as far as I know.

We have a bug report open for this with the vstest team 😉😉😉

**Comment by psfinaki** [comment] 2021-08-18 13:35
Well we don't use the solution run, rather I wrote a script back in a day to glue project runs together heh :D 

I will try to get VsTest logs and verify then. So we could push together :)

**Comment by rouke-broersma** [comment] 2021-08-18 14:09
Well good because solution runs are **not** recommended (because of this problem but also because of inaccuracies).

**Comment by richardwerkman** [comment] 2021-08-18 14:53
This does sound different from issue #1136. We have crashing testrunners there. So lowering the number of testrunners should *increase* the chance of stryker hanging. But you could check. If you find this in strykers logs (not vstest logging) it's the same issue: `[Error] Cancelling the operation as requested.`

**Comment by psfinaki** [comment] 2021-09-08 15:37
@rouke-broersma @richardwerkman okay sorry it took so much time, I was implementing mutation score lock in solution wide and it took a while :D 

Now I got back to this, seems like VsTest is indeed the issue. I cannot collect VsTest logs from the build machine (I guess for that I would need to execute custom Stryker version there?) but I collected Stryker logs for hung executions and I see this `[Error] Cancelling the operation as requested.` there.

Should we try pinging the guys internally?

**Comment by rouke-broersma** [comment] 2021-09-08 16:10
If you could do that, that would be amazing :)

**Comment by psfinaki** [comment] 2021-09-08 16:38
Oh alright. Thanks! I'll see what I can do. This is maybe causing us problems even with running unit tests, we're investigating this now. I'll keep you posted on that.

**Comment by richardwerkman** [comment] 2021-11-02 19:55
@psfinaki Could you try pushing the vstest team again? I've been trying for over a year now but the issue is still open... Maybe with some internal force we can get this issue out of our way 👼

**Comment by psfinaki** [comment] 2021-11-03 12:25
Yyyyep, taking action right now :)

**Comment by psfinaki** [comment] 2021-11-03 13:11
Okay so they are working on that and should update you in that issue - I've subscribed to the PR mentioned there so will follow as well.

**Comment by richardwerkman** [comment] 2021-11-03 17:29
Thanks! Let's hope we can go forward quickly!

**Comment by psfinaki** [comment] 2022-02-18 14:42
The [sound of merging](https://github.com/microsoft/vstest/pull/3349) touched me today :)
We are getting closer.

**Comment by psfinaki** [comment] 2022-02-18 15:10
Well so VS17.1 is out there a few days now and they wanted to have this thing along with VS17.2. That's as much as I know :shrug:

**Comment by richardwerkman** [comment] 2022-02-18 15:16
Great! Thanks for the info

**Comment by psfinaki** [comment] 2022-04-12 11:55
So! How about releasing this? :)

**Comment by rouke-broersma** [comment] 2022-04-12 12:05
Yep, just waiting to see if 0xced replies today on their pr

**Comment by rouke-broersma** [comment] 2022-04-12 20:09
1.5.1 has been released with the workaround for the testrunner freezing, please give it a try

**Comment by psfinaki** [comment] 2022-04-14 09:58
Will do soon, things are a bit slow now because of Easter :)

**Closed** 2022-04-21 09:54 UTC
Labels: 🐛 Bug, Workaround

**Comment by psfinaki** [comment] 2022-04-21 11:49
So I've run our nightly mutation testing three times without concurrency limitations and yes looks like the freezes are gone. Our build machines are kind of random now so the times vary wildly and thus we are yet benefitting from this freedom but still wanted to confirm this.
