### ISSUE TITLE
Support grpc client code generated from proto files

### ISSUE THREAD

**Issue by extesy** [stryker-mutator/stryker-net#2235] opened 2022-10-05 17:31 UTC
**Describe the bug**
A working (syntactically valid) project can't be mutated by Stryker. Fails with `Internal error due to compile error`. At the same time `dotnet test` passes without any issues. 

**Logs**
Unfortunately I can't attach full logs because they contain the source code which I can't share. All errors are pretty much of the same kind:
* The type or namespace name '...' could not be found (are you missing a using directive or an assembly reference?)
* The name '...' does not exist in the current context

**Expected behavior**
Successful project mutation.

**Desktop (please complete the following information):**
 - OS: Windows
 - Type of project: core
 - Framework Version: .net 6
 - Stryker Version: 3.0.1

**Additional context**
The project contains autogenerated grpc client code from the *.proto definitions. Missing types all come from those files. It's like Styker completely skips that autogeneration step during the mutation.

**Comment by rouke-broersma** [comment] 2022-10-05 19:09
Because we compile manually we have to reintroduce ways to collect project contents that don't come from source code. Could you provide us with a sample project containing grpc, and point us to what the grpc sources should look like once compiled and packaged (ilspy screenshot or something)?

**Comment by ysbakker** [comment] 2022-10-28 18:50
Investigating this

**Comment by ysbakker** [comment] 2022-10-29 09:22
I was unable to reproduce this issue. I created a minimal reproducible example [here](https://github.com/ysbakker/GrpcTestProject). Running `dotnet stryker` in these projects does not give me any of the issues you described. 

I'm using a client and server project that both have tests that reference and use the classes generated from the protofiles. I noticed there are a few ways to share the protofiles among your projects, so there might be some differences with the project you use here? Let me know if I can improve the example project to more accurately reproduce your environment.

**Comment by extesy** [comment] 2022-10-31 19:24
@ysbakker Thank you for looking into this. Here is the redacted log file from Stryker and two csproj file (unit tests and the main project): https://gist.github.com/extesy/3d52c04ba4471009f81a81edaf6aa1ce. I've removed log lines which included source code and stopped it at the first error. Hopefully that should provide more data for analysis. The specific command line I ran is:
```
dotnet stryker --log-to-file --mutation-level complete --concurrency 1 --verbosity warning --mutate !*.g.cs
```
 Thanks again and please let me know if there is a way to generate logs without source code, then I could provide a full log.

**Comment by ysbakker** [comment] 2022-11-12 15:44
Can you confirm that the namespaces that are not found are **all** generated based on `proto` files?

For documentative purposes; the namespace errors seem to start here:
https://gist.github.com/extesy/3d52c04ba4471009f81a81edaf6aa1ce#file-log-20221031-txt-L4006

**Comment by extesy** [comment] 2022-11-12 16:12
@ysbakker Yes all of them come from the generated proto files.

**Comment by ysbakker** [comment] 2022-11-17 19:12
I see, thanks for the information. At this time, I can't reproduce the issue and don't really know where else to look, so I'm unassigning myself for now. I hope someone else can give more insight

**Comment by dupdob** [comment] 2024-07-08 08:51
the core of the problem here is that some cs files are generated via special MsBuild tasks (and/or target):
```
  Generated CSharp file C:\Git\collectibles\services\collectibles-item-service\src/../obj/CollectiblesItemService/Debug\net6.0\.ps.g\Roblox\Collectibles\Item\Entities\CollectibleItems.ps.g.cs
  Generated CSharp file C:\Git\collectibles\services\collectibles-item-service\src/../obj/CollectiblesItemService/Debug\net6.0\.ps.g\Roblox\Collectibles\Item\Entities\TargetType.ps.g.cs
  Generated CSharp file C:\Git\collectibles\services\collectibles-item-service\src/../obj/CollectiblesItemService/Debug\net6.0\.ps.g\Roblox\Collectibles\Item\Entities\CollectibleItemInstances.ps.g.cs
  Generated CSharp file C:\Git\collectibles\services\collectibles-item-service\src/../obj/CollectiblesItemService/Debug\net6.0\.ps.g\Roblox\Collectibles\Item\Entities\ItemConfiguration.ps.g.cs
  Generated CSharp file C:\Git\collectibles\services\collectibles-item-service\src/../obj/CollectiblesItemService/Debug\net6.0\.ps.g\Roblox\Collectibles\Item\Entities\ItemConfigurations.ps.g.cs
  Generated CSharp file C:\Git\collectibles\services\collectibles-item-service\src/../obj/CollectiblesItemService/Debug\net6.0\.ps.g\Roblox\Collectibles\Item\Entities\CollectibleItem.ps.g.cs
  Generated CSharp file C:\Git\collectibles\services\collectibles-item-service\src/../obj/CollectiblesItemService/Debug\net6.0\.ps.g\Roblox\Collectibles\Item\Entities\CollectibleItemInstanceExternalSystem.ps.g.cs
  Generated CSharp file C:\Git\collectibles\services\collectibles-item-service\src/../obj/CollectiblesItemService/Debug\net6.0\.ps.g\Roblox\Collectibles\Item\Entities\CollectibleItemInstance.ps.g.cs
  Generated CSharp file C:\Git\collectibles\services\collectibles-item-service\src/../obj/CollectiblesItemService/Debug\net6.0\.ps.g\Roblox\Collectibles\Item\Entities\CollectibleItemInstanceExternalSystems.ps.g.cs
```
I have yet to try the project, so I am not sure if Buildalyzer lists theses as source files, but one thing is sure: those are removed when doing build analysis, as Buildalyzer requires to perform a clean build.
As such, they will be missing for the mutation phase and will trigger compilation errors.

**Comment by dupdob** [comment] 2024-07-08 09:44
I just tested the repro project, and warnings are gone. This means the issue has probably been fixed by recent changes. This is credible as the build and analyze stages have been significantly redesigned in the past month.
I am closing this issue as it appears to be fixed, but feel free to reopen it if you still have issues with latest Stryker versions (4.0.6+)

**Closed by dupdob** 2024-07-08 09:44 UTC
Labels: 🚀 Feature request, Repro needed, ! Need more info !

**Comment by Steellkek** [comment] 2025-04-21 06:39
Hello, I'm trying to test my gRPC server, but the project containing the proto file throws an exception:
`2025-04-21T09:07:21.8081827+03:00  [DBG] "The type or namespace name 'Proto' does not exist in the namespace 'BillingGkh.Asco' (are you missing an assembly reference?)", "SourceFile(C:\Users\A.minikaev\RiderProjects\BillingGkh.Asco\src\BillingGkh.Asco.Core\DomainService\TemplateService.cs[377..382))" (c689eebb)`

For file generation, we're using protobuf-net.BuildTools. 
The file path in the .csproj looks like this:
`<AdditionalFiles Include="Proto\Server\template_service.proto"> <Services>true</Services><ListSet>true</ListSet> </AdditionalFiles>`
