### ISSUE TITLE
Exception thrown by LocalFunctionStatementOrchestrator in CLI 1.5.0

### ISSUE THREAD

**Issue by yellowfog** [stryker-mutator/stryker-net#1986] opened 2022-04-03 14:24 UTC
**Describe the bug**
When I have a local function defined in a block that also has a block level mutation for another part, the local function tries to implement the mutation and falls over (an InvalidOperationException in RoslynHelper). I suspect that LocalFunctionStatementOrchestrator should have the same override of PrepareContext as AnonymousFunctionExpressionOrchestrator (this fixes the problem in my example), but I don't know the code well enough to know if this is truly the right fix.

**Additional context**
Please see the attached zip file (containing a small VS 2022 solution) for a replication of the bug.

[BreakStryker.zip](https://github.com/stryker-mutator/stryker-net/files/8404699/BreakStryker.zip)

**Comment by dupdob** [comment] 2022-04-03 20:31
duplicate of #1978

**Comment by yellowfog** [comment] 2022-04-04 06:46
Hi - I was working off master, which I made sure to pull before running the code. This isn't a duplicate of 1978, because that fixed the AnonymousFunctionExpressionOrchestrator. This shows that a similar problem affects the LocalFunctionStatementOrchestrator. Did you not try running my example?

**Comment by dupdob** [comment] 2022-04-04 08:38
Sorry about that. It looked a lot like #1978 for which the fix has not been released yet. 
I am looking into this now.
Had I known this was replicated with 'master', I would obviously not have closed it.

**Comment by yellowfog** [comment] 2022-04-04 09:44
My bad, should have made that clear in my write-up

**Comment by dupdob** [comment] 2022-04-04 12:38
No worries, there was several hints in your issue's description. It just happens that I have fixed a similar bug hence I jumped to conclusions. BTW this makes me realize a more ambitious fix is needed to prevent it creep again

**Comment by dupdob** [comment] 2022-04-05 07:29
BTW: you should be able to work around this issue using a block body form for your local function instead of the arrow expression.

Actually, this issue is a bit trickier than it looks. I mean, my PR fixes this issue by providing a `preparecontext` implementation, but it will be redundant and ill placed for block body local and anonymous functions.

**Closed** 2022-04-12 06:03 UTC
Labels: 🐛 Bug, Area: Mutating
