### ISSUE TITLE
Project not building with Stryker

### ISSUE THREAD

**Issue by AshleighAdams** [stryker-mutator/stryker-net#2345] opened 2022-12-01 22:15 UTC
**Describe the bug**
When running locally, Stryker builds and tests things fine (Windows), but on GitHub Actions, a compile error is generated. In particular, it looks to be related with a standard2.0 compatibility library for adding nullable annotations (https://github.com/manuelroemer/Nullable)

**Logs**

```
[21:32:08 WRN] Stryker.NET encountered an compile error in /home/runner/work/Verlite/Verlite/src/Verlite.Core/SemVer.cs (at 80:45) with message: The type or namespace name 'NotNullWhenAttribute' could not be found (are you missing a using directive or an assembly reference?) (Source code: NotNullWhen)
```

Stryker log is attached.

**Expected behavior**
Mutation testing to complete sucessfully as it does when running locally on my Windows machine.

**Desktop (please complete the following information):**
 - OS: Linux
 - Type of project: standard 2.0
 - Framework version: dotnet 6 or 7
 - Stryker version: 3.2.0

**Additional context**
The exact project setup can be found here: https://github.com/AshleighAdams/Verlite/actions/runs/3596938533/jobs/6058181386

Additionally, this bug looks to be related: https://github.com/manuelroemer/Nullable/issues/24
[StrykerOutput.zip](https://github.com/stryker-mutator/stryker-net/files/10136532/StrykerOutput.zip)

**Comment by rouke-broersma** [comment] 2022-12-02 08:29
Linked issues seem to suggest this is related to ContentFiles, and is fixed in a newer version of Nullable. Do you have this issue with the latest version?

**Comment by rouke-broersma** [comment] 2022-12-02 11:26
So this problem is fixed?

**Comment by AshleighAdams** [comment] 2022-12-02 13:58
Nope, sorry, I was experiencing the linked bug where it wasn't building until I updated to the fixed version. The fixed version that now otherwise builds fails with Stryker.

**Comment by rouke-broersma** [comment] 2022-12-02 17:03
We probably don't search ContentFiles for source code.

**Comment by Liam-Rougoor** [comment] 2022-12-09 12:16
@AshleighAdams I've been looking into a little, it seems that if you run the action on Windows instead of Linux, this error/issue does not occur (just like how it works on your local Windows machine). I have not yet found the cause of this issue, but this could be a temporary workaround for you.

**Comment by AshleighAdams** [comment] 2022-12-13 20:29
Thanks, that workaround works for me :)

**Comment by FrediKats** [comment] 2024-05-05 11:27
Faced with the same problem. CI doesn't work on Ubuntu and works on Windows. PR with confirm attached.

**Comment by rouke-broersma** [comment] 2024-07-05 13:41
ContentFiles should now be supported

**Closed by rouke-broersma** 2024-07-05 13:41 UTC
Labels: 🐛 Bug, Workaround
