### ISSUE TITLE
MSBUILD : error MSB1009: Project file does not exist.

### ISSUE THREAD

**Issue by chertby** [stryker-mutator/stryker-net#2063] opened 2022-05-19 08:26 UTC
**Describe the bug**

Error when launching stryker from a solution folder.

**Logs**

```txt
Stryker.NET failed to mutate your project. For more information see the logs below:


Microsoft (R) Build Engine version 17.2.0+41abc5629 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: AL.StrykerMutator.sln


Initial build of targeted project failed. Please make sure the targeted project is buildable. You can reproduce this error yourself using: "dotnet    
build "AL.StrykerMutator.ConsoleAppTests.csproj""
```

**Expected behavior**

Solution has several projects and several test projects, which are separated into folders, we want to configure the launch of the `Stryker mutator` for some test projects.

**Desktop (please complete the following information):**

 - OS: `Windows`
 - Type of project `core`
 - Framework Version `net6.0`
 - Stryker Version `1.5.3`

**Additional context**

```text
folder
│
└───src
│   └───AL.StrykerMutator.ConsoleApp
│       │   AL.StrykerMutator.ConsoleApp.csproj
│       │   Calc.cs
│
└───test
|   │
|   └───AL.StrykerMutator.ConsoleAppTests
|   │   │   CalcTests.cs
|   │ 
|   │  stryker-config.json
| 
|   AL.StrykerMutator.sln
```

```bash
dotnet stryker --open-report --config-file "test/stryker-config.json"
```

```json
{
    "stryker-config":
    {
        "solution": "AL.StrykerMutator.sln",
        "project": "AL.StrykerMutator.ConsoleApp.csproj",
        "test-projects": ["test/AL.StrykerMutator.ConsoleAppTests/AL.StrykerMutator.ConsoleAppTests.csproj"]
    }
}
```

**Comment by davidchavezgrant** [comment] 2022-06-23 05:23
I'm receiving the same error when running stryker from the project under test, while specifying the test projects: 

```json
{
  "stryker-config":
  {
    "solution": "../../../../MySolution.sln",
    "project": "ProjectInCurrentDirectory.csproj",
    "mutation-level": "Complete",
    "thresholds" : {"high": 80, "low": 70, "break": 60},
    "test-projects":
    [
      "../../../../tests/ProjectInCurrentDirectory.Tests.Unit/ProjectInCurrentDirectory.Tests.Unit.csproj",
      "../../../../tests/ProjectInCurrentDirectory.Tests.Integration/ProjectInCurrentDirectory.Tests.Integration.csproj"
    ]
  }
}
```

**Comment by rouke-broersma** [comment] 2022-08-05 07:51
This seems to be a duplicate of #1976

**Closed by rouke-broersma** 2022-08-05 07:51 UTC
Labels: 🐛 Bug, Priority: Medium
