### ISSUE TITLE
--diff mutates entire project because "Non-csharp files in the test project were changed"

### ISSUE THREAD

**Issue by eranrodrig-tipalti** [stryker-mutator/stryker-net#1204] opened 2020-09-14 14:51 UTC
**Describe the bug**
--diff mutates entire project because "Non-csharp files in the test project were changed", but actually no files were changed in the test project. Even if that were the case, I'd like to have the option to still run diff.
I've attached a log in which only auto generated stryker files were added to the test project, but it also happened to me when I put these files in gitignore and even when I ran stryker from another directory.

**Logs**
Attached.

**Expected behavior**
I'd expect the diff to run as usual, without mutating the entire project.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Type of project: dotnet Core
 - Framework Version: 3.1
 - Stryker Version: 0.19

**Additional context**
[log-20200914.txt](https://github.com/stryker-mutator/stryker-net/files/5219194/log-20200914.txt)

**Comment by Mobrockers** [comment] 2020-09-14 15:00
Hi! This is a duplicate of #1188

A workaround has been merged and will be released soon

**Closed by Mobrockers** 2020-09-14 15:00 UTC
Labels: bug
